package fpga.host.exporters

import fpga.host.models._
import fpga.host.transform.MemoryLayout

/** Rendering + staging for the runtime SD-card loader manifest. Translated from
  * host/nnbaremetal/emit_sd.py. Unlike the header-only artifacts this both
  * writes `nn_sd_manifest.h` and copies the referenced `.bin` set under
  * `sdCardDir`, so it has a bespoke [[Exportable]] (see [[SdEmitters]]).
  */
private[exporters] object SdRender {

  private def fileSize(binPath: String, fallback: Long): Long = {
    val p = os.Path(binPath, os.pwd)
    if (os.isFile(p)) Model.fileSizeOr0(binPath)
    else {
      println(s"WARNING: $binPath not found - using CSV size $fallback")
      fallback
    }
  }

  /** Manifest header text, the absolute source paths to stage, and the staging
    * root directory. The caller (the `Exportable`) writes the header and copies
    * the staged files.
    */
  def build(t: SdManifest): (String, Seq[String], os.Path) = {
    val layers = t.layers
    val ddrBase = t.ddrBase
    val compDir = t.compDir
    val emitRefs = t.emitRefs

    val sub = t.sdDir.stripPrefix("/").stripSuffix("/")
    val nnSdDir = if (sub.nonEmpty) sub + "/" else ""

    // Build static buffer entries and staged paths together.
    val staticAndPaths: Seq[((String, Long, Long), String)] =
      Model
        .iterStaticBuffers(layers)
        .map { case (_, layer, bufType, m) =>
          val binPath = os.Path(layer.binFiles(bufType), os.pwd).toString
          val name = os.Path(binPath).last
          val addr = ddrBase + m.offset
          ((name, addr, fileSize(binPath, m.byteSize)), binPath)
        }
        .toSeq ++
        // CPU-op parameter blobs (convtranspose float weights/bias)
        t.extraBlobs.map { b =>
          val binPath = os.Path(b.path, os.pwd).toString
          val name = os.Path(binPath).last
          ((name, b.addr, fileSize(binPath, b.size)), binPath)
        }
    val static = staticAndPaths.map(_._1)
    val staticPaths = staticAndPaths.map(_._2)

    // Raw network input (optional)
    val inputPath = os.Path(s"$compDir/input_nn.bin", os.pwd).toString
    val hasInput =
      os.exists(os.Path(inputPath)) && os.isFile(os.Path(inputPath))
    val inputEntry: Option[(String, Long, Long)] =
      if (hasInput) {
        val sz = os.size(os.Path(inputPath))
        Some(("input_nn.bin", MemoryLayout.scratchAddr(layers, ddrBase), sz))
      } else None
    val inputPaths: Seq[String] = inputEntry.map(_ => inputPath).toSeq

    // Isolation-debug golden references
    val refsAndPaths: Seq[((String, Long, Long), String)] = if (emitRefs) {
      layers.flatMap { layer =>
        val outEntry = layer.check
          .filter(c => c.outRefSize > 0 && c.outRefFile.nonEmpty)
          .map { c =>
            val outAbs = os.Path(c.outRefFile, os.pwd).toString
            (
              (
                os.Path(outAbs).last,
                c.outRefAddr,
                fileSize(outAbs, c.outRefSize)
              ),
              outAbs
            )
          }
        val inEntry = layer.check
          .filter(c => c.inRefSize > 0 && c.inRefFile.nonEmpty)
          .map { c =>
            val inAbs = os.Path(c.inRefFile, os.pwd).toString
            (
              (os.Path(inAbs).last, c.inRefAddr, fileSize(inAbs, c.inRefSize)),
              inAbs
            )
          }
        outEntry.toSeq ++ inEntry.toSeq
      }
    } else Nil
    val refs = refsAndPaths.map(_._1)
    val refPaths = refsAndPaths.map(_._2)

    val staged = staticPaths ++ inputPaths ++ refPaths

    val headerLines = Seq(
      "/* Auto-generated by gen_nn_baremetal.py - DO NOT EDIT */",
      "/*",
      " * SD-card manifest: file -> DDR address map for the runtime sd loader",
      " * (driver/src/vta_sd.cc). Copy the staged files in gen/sd_card/ to the",
      " * root of a FAT32 SD card, then run a DATA_LOADER=sd build.",
      " */",
      "#ifndef NN_SD_MANIFEST_H",
      "#define NN_SD_MANIFEST_H",
      "#include \"vta_sd.h\"",
      "",
      "/* SD subfolder the files live in (path prefix, trailing slash); empty",
      " * = card root. The app opens \"0:/\" NN_SD_DIR <filename>. */",
      s"""#define NN_SD_DIR "$nnSdDir"""",
      "",
      "static const vta::SdFile nn_sd_static_files[] = {"
    )
    val staticFileLines = static.map { case (name, addr, size) =>
      s"""    {"$name", ${Model.hex32(addr)}, ${size}u},"""
    }
    val staticFooter = Seq(
      "};",
      s"#define NN_SD_NUM_STATIC ${static.size}u",
      ""
    )
    val inputLines: Seq[String] = inputEntry match {
      case Some((name, addr, size)) =>
        Seq(
          "#define NN_SD_HAS_INPUT 1",
          s"""static const vta::SdFile nn_sd_input_file = {"$name", ${Model
              .hex32(addr)}, ${size}u};"""
        )
      case None => Seq("#define NN_SD_HAS_INPUT 0")
    }
    val refLines: Seq[String] = if (refs.nonEmpty) {
      Seq(
        "",
        "/* fsim golden input/output per VTA layer, loaded to the same",
        " * reserved-DRAM addresses as nn_debug_map.h's in/out_ref_phys.",
        " * Used by run_nn_debug / run_nn_cpu_debug under DATA_LOADER=sd. */",
        "#define NN_SD_HAS_REFS 1",
        "static const vta::SdFile nn_sd_ref_files[] = {"
      ) ++
        refs.map { case (name, addr, size) =>
          s"""    {"$name", ${Model.hex32(addr)}, ${size}u},"""
        } ++
        Seq(
          "};",
          s"#define NN_SD_NUM_REF ${refs.size}u"
        )
    } else {
      Seq("", "#define NN_SD_HAS_REFS 0")
    }
    val footerLines = Seq("", "#endif /* NN_SD_MANIFEST_H */")

    val content =
      (headerLines ++ staticFileLines ++ staticFooter ++ inputLines ++ refLines ++ footerLines)
        .mkString("\n") + "\n"

    val stageRoot =
      if (sub.nonEmpty) os.Path(t.sdCardDir, os.pwd) / sub
      else os.Path(t.sdCardDir, os.pwd)

    (content, staged, stageRoot)
  }
}

/** `Exportable` instance for the SD manifest: write the header to `path`, then
  * stage the referenced binaries under `sdCardDir`.
  */
trait SdEmitters {
  implicit val sdManifestIsExportable: Exportable[SdManifest] =
    Exportable { (t: SdManifest, path: os.Path) =>
      {
        val (content, staged, stageRoot) = SdRender.build(t)
        os.write.over(path, content)
        val sub = t.sdDir.stripPrefix("/").stripSuffix("/")
        println(s"[gen] SD manifest written to $path")

        // Stage the referenced binaries into sdCardDir/<sdDir>/
        if (os.exists(stageRoot)) os.remove.all(stageRoot)
        os.makeDir.all(stageRoot)
        for (src <- staged) {
          val srcPath = os.Path(src, os.pwd)
          os.copy(
            srcPath,
            stageRoot / srcPath.last,
            replaceExisting = true,
            createFolders = true
          )
        }
        val dstHint =
          if (sub.nonEmpty) s"the SD card's $sub/ folder"
          else "the SD card root"
        println(
          s"[gen] staged ${staged.size} file(s) into $stageRoot" +
            s" - copy its contents to $dstHint"
        )
      }
    }
}
