package fpga.synthesis

object BoardParams {
  private def br(v: String): String = "{" + v + "}"

  def render(
    b: Board,
    vtaCell: String,
    vtaVlnv: String,
    ipRepo: String,
    outDir: String,
    projDir: String,
    jobs: Int
  ): String = {
    def subst(s: String): String =
      s.replace("{ps_cell}", b.psCell).replace("{vta_cell}", vtaCell)
    val sb = new StringBuilder
    def line(s: String): Unit = { sb.append(s); sb.append("\n") }
    val repo =
      if (b.boardRepo.isEmpty) ""
      else b.boardRepo.replaceFirst("^~", System.getProperty("user.home"))
    val psCfg = b.psConfig.map { case (k, v) => s"$k ${br(v)}" }.mkString(" ")
    // NoC config deltas (Versal). Mirrors build_fpga.py: when the board omits
    // noc_config, fall back to the same default LPDDR4 dict, in the same order.
    val nocPairs =
      if (b.nocConfig.nonEmpty) b.nocConfig
      else
        Seq(
          "MC2_FLIPPED_PINOUT" -> "true",
          "MC_CHANNEL_INTERLEAVING" -> "true",
          "MC_CHAN_REGION1" -> "DDR_LOW1",
          "MC_LP4_OVERWRITE_IO_PROP" -> "true",
          "MC_LP4_PIN_EFFICIENT" -> "true",
          "MC_SYSTEM_CLOCK" -> "Differential"
        )
    val nocCfg = nocPairs.map { case (k, v) => s"$k ${br(v)}" }.mkString(" ")
    // Versal external memory interface ports, emitted for every board (the
    // recipe only reads them under is_versal). Defaults match build_fpga.py.
    val versalLines = Seq(
      "versal_ch0" -> "ch0_lpddr4_trip1",
      "versal_ch1" -> "ch1_lpddr4_trip1",
      "versal_clk" -> "lpddr4_clk1"
    ).map { case (k, dflt) => s"set $k ${br(b.ports.getOrElse(k, dflt))}" }
      .mkString("\n")
    val portKeys = Seq(
      "port_vta_dram_master" -> "vta_dram_master",
      "port_vta_ctrl_slave" -> "vta_ctrl_slave",
      "port_vta_clk" -> "vta_clk",
      "port_vta_resetn" -> "vta_resetn",
      "port_ps_dram_slave" -> "ps_dram_slave",
      "port_ps_ctrl_master" -> "ps_ctrl_master",
      "port_ps_clk" -> "ps_clk",
      "port_ps_resetn" -> "ps_resetn"
    )
    val addrItems = b.addresses
      .map { case (sp, seg, off, rng) =>
        "{" + s"${subst(sp)} ${subst(seg)} $off $rng" + "}"
      }
      .mkString(" ")

    val exclItems = b.addressExcludes
      .map { case (sp, seg) =>
        "{" + s"${subst(sp)} ${subst(seg)}" + "}"
      }
      .mkString(" ")
    s"""# board_params.tcl - generated by build_fpga.py; do not edit by hand.
       |# board: ${b.name}
       |
       |set board_name ${br(b.name)}
       |set part ${br(b.part)}
       |set board_part ${br(b.boardPart)}
       |set is_versal ${br(b.isVersal.toString.toLowerCase)}
       |set ps_ip ${br(b.psIp)}
       |set ps_cell ${br(b.psCell)}
       |set ps_preset_rule ${br(b.psPresetRule)}
       |set ps_preset_config ${br(b.psPresetConfig)}
       |set board_repo ${br(repo)}
       |set pl_clock_mhz ${br(b.plClockMhz)}
       |set pl_clock_property ${br(b.plClockProperty)}
       |set vta_cell ${br(vtaCell)}
       |set vta_vlnv ${br(vtaVlnv)}
       |set ip_repo ${br(ipRepo)}
       |set out_dir ${br(outDir)}
       |set proj_dir ${br(projDir)}
       |set jobs ${br(jobs.toString)}
       |
       |set ps_config {$psCfg}
       |set noc_config {$nocCfg}
       |${portKeys
        .map { case (tclKey, jsonKey) =>
          s"set $tclKey ${br(b.ports.getOrElse(jsonKey, sys.error(s"board ${b.name} missing port '$jsonKey'")))}"
        }
        .mkString("\n")}
       |$versalLines
       |set ps_clk_aclks {${b.psClkAclks.mkString(" ")}}
       |
       |set addresses {${addrItems}}
       |set address_excludes {${exclItems}}
       |""".stripMargin
  }
}
