package fpga.synthesis

object BoardParams {
  private def br(v: String): String = "{" + v + "}"

  def render(
    b: Board,
    vtaCell: String,
    vtaVlnv: String,
    ipRepo: String,
    outDir: String,
    projDir: String,
    jobs: Int
  ): String = {
    def subst(s: String): String =
      s.replace("{ps_cell}", b.psCell).replace("{vta_cell}", vtaCell)
    val sb = new StringBuilder
    def line(s: String): Unit = { sb.append(s); sb.append("\n") }
    val repo =
      if (b.boardRepo.isEmpty) ""
      else b.boardRepo.replaceFirst("^~", System.getProperty("user.home"))
    val psCfg = b.psConfig.map { case (k, v) => s"$k ${br(v)}" }.mkString(" ")
    val portKeys = Seq(
      "port_vta_dram_master" -> "vta_dram_master",
      "port_vta_ctrl_slave" -> "vta_ctrl_slave",
      "port_vta_clk" -> "vta_clk",
      "port_vta_resetn" -> "vta_resetn",
      "port_ps_dram_slave" -> "ps_dram_slave",
      "port_ps_ctrl_master" -> "ps_ctrl_master",
      "port_ps_clk" -> "ps_clk",
      "port_ps_resetn" -> "ps_resetn"
    )
    val addrItems = b.addresses
      .map { case (sp, seg, off, rng) =>
        "{" + s"${subst(sp)} ${subst(seg)} $off $rng" + "}"
      }
      .mkString(" ")

    val exclItems = b.addressExcludes
      .map { case (sp, seg) =>
        "{" + s"${subst(sp)} ${subst(seg)}" + "}"
      }
      .mkString(" ")
    s"""# board_params.tcl - generated by build_fpga.py; do not edit by hand.
       |# board: ${b.name}
       |
       |set board_name ${br(b.name)}
       |set part ${br(b.part)}
       |set board_part ${br(b.boardPart)}
       |set is_versal ${br(b.isVersal.toString.toLowerCase)}
       |set ps_ip ${br(b.psIp)}
       |set ps_cell ${br(b.psCell)}
       |set ps_preset_rule ${br(b.psPresetRule)}
       |set ps_preset_config ${br(b.psPresetConfig)}
       |set board_repo ${br(repo)}
       |set pl_clock_mhz ${br(b.plClockMhz)}
       |set pl_clock_property ${br(b.plClockProperty)}
       |set vta_cell ${br(vtaCell)}
       |set vta_vlnv ${br(vtaVlnv)}
       |set ip_repo ${br(ipRepo)}
       |set out_dir ${br(outDir)}
       |set proj_dir ${br(projDir)}
       |set jobs ${br(jobs.toString)}
       |
       |set ps_config {$psCfg}
       |${portKeys
        .map { case (tclKey, jsonKey) =>
          s"set $tclKey ${br(b.ports.getOrElse(jsonKey, sys.error(s"board ${b.name} missing port '$jsonKey'")))}"
        }
        .mkString("\n")}
       |set ps_clk_aclks {${b.psClkAclks.mkString(" ")}}
       |
       |set addresses {${addrItems}}
       |set address_excludes {${exclItems}}
       |""".stripMargin
  }
}
