package fpga.synthesis

import scopt.OParser

/** OOC-synthesize an emitted shell (default VTAXilinxShell) to a gate-level
  * netlist for the post-synth sim flow. Ported from postsynth/synth_netlist.sh.
  *
  * Renders ooc_params.tcl from a boards/<board>.json part + pl_clock_mhz, then
  * runs the classpath ooc_netlist.tcl recipe under Vivado, producing
  * <out>/<top>_funcsim.v (mode=synth), or also <top>_timesim.v + .sdf
  * (mode=impl).
  */
object OocNetlist {

  def main(args: Array[String]): Unit = sys.exit(run(args))

  private case class Opts(
    board: String = "zcu104",
    svDir: Option[String] = None,
    top: String = "VTAXilinxShell",
    clkPort: String = "ap_clk",
    out: Option[String] = None,
    projDir: Option[String] = None,
    mode: String = "synth",
    jobs: Int = 8,
    vivado: String = Vivado.tool(sys.env, "vivado"),
    dryRun: Boolean = false
  )

  private val argParser: OParser[_, Opts] = {
    val b = OParser.builder[Opts]
    import b._
    OParser.sequence(
      programName("oocNetlist"),
      opt[String]("board").action((x, c) => c.copy(board = x)),
      opt[String]("sv-dir")
        .action((x, c) => c.copy(svDir = Some(x)))
        .text(
          "emitted SV dir holding <top>.sv (default: the debug-xilinx-shell emit)"
        ),
      opt[String]("top").action((x, c) => c.copy(top = x)),
      opt[String]("clk-port").action((x, c) => c.copy(clkPort = x)),
      opt[String]("out").required().action((x, c) => c.copy(out = Some(x))),
      opt[String]("proj-dir")
        .action((x, c) => c.copy(projDir = Some(x)))
        .text("Vivado OOC project dir (default <out>/proj)"),
      opt[String]("mode")
        .action((x, c) => c.copy(mode = x))
        .validate(m =>
          if (m == "synth" || m == "impl") success
          else failure("--mode must be synth or impl")
        ),
      opt[Int]("jobs").action((x, c) => c.copy(jobs = x)),
      opt[String]("vivado").action((x, c) => c.copy(vivado = x)),
      opt[Unit]("dry-run").action((_, c) => c.copy(dryRun = true))
    )
  }

  /** Render ooc_params.tcl. clk_period_ns = 1000 / pl_clock_mhz. */
  def renderParams(
    part: String,
    svDir: String,
    top: String,
    outDir: String,
    projDir: String,
    clkPort: String,
    plClockMhz: String,
    mode: String,
    jobs: Int
  ): String = {
    val periodNs = 1000.0 / plClockMhz.toDouble
    s"""# auto-generated by fpga.synthesis.OocNetlist - do not edit
       |set part          $part
       |set sv_dir        $svDir
       |set top           $top
       |set out_dir       $outDir
       |set proj_dir      $projDir
       |set clk_port      $clkPort
       |set clk_period_ns $periodNs
       |set mode          $mode
       |set jobs          $jobs
       |""".stripMargin
  }

  def run(argv: Array[String]): Int = {
    val repoRoot = sys.env.get("VTA_ROOT").map(os.Path(_)).getOrElse(os.pwd)
    val boardsDir = repoRoot / "vta" / "fpga" / "boards"
    val oocTcl =
      Vivado.extractResource("synthesis/ooc_netlist.tcl", "-ooc_netlist.tcl")

    val o = OParser.parse(argParser, argv, Opts()) match {
      case Some(parsed) => parsed
      case _            => return 1
    }

    val board = Board.load((boardsDir / s"${o.board}.json").toString)
    val svDir = os.Path(
      o.svDir.getOrElse(
        (repoRoot / "build" / "emitted" / "vta-debug-xilinx-shell").toString
      ),
      os.pwd
    )
    val outDir = os.Path(o.out.get, os.pwd)
    val projDir = o.projDir.map(os.Path(_, os.pwd)).getOrElse(outDir / "proj")

    if (!o.dryRun && !os.exists(svDir / s"${o.top}.sv")) {
      System.err.println(
        s"ERROR: ${svDir / s"${o.top}.sv"} missing (emit it first)"
      )
      return 1
    }

    val params = renderParams(
      board.part,
      svDir.toString,
      o.top,
      outDir.toString,
      projDir.toString,
      o.clkPort,
      board.plClockMhz,
      o.mode,
      o.jobs
    )
    val paramsFile = outDir / "ooc_params.tcl"
    println(
      s"[oocNetlist] board=${o.board} part=${board.part} top=${o.top} mode=${o.mode} sv_dir=$svDir out=$outDir"
    )
    if (o.dryRun) {
      println("\n--- generated ooc_params.tcl ---")
      println(params)
      println("--- end ooc_params.tcl ---")
    } else {
      os.makeDir.all(outDir)
      os.write.over(paramsFile, params)
    }

    Vivado.runCmd(
      Seq(
        o.vivado,
        "-mode",
        "batch",
        "-source",
        oocTcl,
        "-tclargs",
        paramsFile.toString,
        "-log",
        (outDir / "vivado.log").toString,
        "-journal",
        (outDir / "vivado.jou").toString
      ),
      cwd = outDir,
      dryRun = o.dryRun,
      stage = s"ooc synth ${o.top}"
    )
    if (!o.dryRun)
      println(s"[oocNetlist] netlist -> ${outDir / s"${o.top}_funcsim.v"}")
    0
  }
}
