/**
 * run_nn.cc — Multi-layer VTA inference (XSCT method).
 *
 * DDR memory is pre-initialized via the XSCT script generated by
 * tools/gen_nn_baremetal.py (load_nn.tcl): static model data (INSN/UOP/WGT/ACC)
 * and input_nn.bin are loaded before this binary starts.
 *
 * Execution follows the typed plan in nn_exec_plan.h, which is derived from
 * dependency.csv and handles both VTA layers and ARM CPU operations in order.
 *
 * To regenerate headers from a compiler output directory:
 *   python3 tools/gen_nn_baremetal.py <compiler_output_dir>       \
 *       --ddr-base 0x10000000                                      \
 *       --out-header    src/fpga/software/examples/nn_ddr_map.h   \
 *       --out-tcl       src/fpga/software/examples/load_nn.tcl    \
 *       --out-exec-plan src/fpga/software/examples/nn_exec_plan.h
 */

#include "nn_ddr_map.h"       // generated — LayerDesc nn_layers[], NN_NUM_LAYERS
#include "nn_exec_plan.h"     // generated — NnExecStep nn_exec_steps[], NN_NUM_STEPS
#include "../include/vta_nn.h"
#include "../include/vta_cpu_ops.h"
#include <cstdlib>
extern "C" {
#include "xil_printf.h"
#include "xparameters.h"
}

constexpr std::uintptr_t VTA_VCR_BASE =
    static_cast<std::uintptr_t>(XPAR_VTADEFAULTSHELL_0_BASEADDR);

int main()
{
    xil_printf("=== VTA NN runner: %u step(s) ===\r\n",
               static_cast<unsigned>(NN_NUM_STEPS));

    float *float_buf = nullptr;

    for (unsigned i = 0u; i < NN_NUM_STEPS; ++i) {
        const NnExecStep &s = nn_exec_steps[i];
        xil_printf("[vta] step %u/%u: %s\r\n", i, NN_NUM_STEPS - 1u, s.name);

        switch (s.type) {
        case NN_STEP_VTA:
            if (vta::run_layer(VTA_VCR_BASE, nn_layers[s.vta.layer_idx]) != 0) {
                xil_printf("=== NN FAILED at step %u ===\r\n", i);
                return -1;
            }
            break;

        case NN_STEP_QADD:
            vta::run_qadd(s.qadd);
            break;

        case NN_STEP_CONCAT:
            vta::run_concat(s.concat, float_buf);
            break;

        case NN_STEP_DEQUANT:
            float_buf = static_cast<float *>(
                std::malloc(s.dequant.n_elems * sizeof(float)));
            if (!float_buf) {
                xil_printf("=== malloc failed at step %u ===\r\n", i);
                return -1;
            }
            vta::run_dequant(s.dequant, float_buf);
            break;

        case NN_STEP_QUANT:
            vta::run_quant(s.quant, float_buf);
            std::free(float_buf);
            float_buf = nullptr;
            break;

        case NN_STEP_FORMAT_INPUT:
            vta::run_format_input(s.format_input);
            break;
        }
    }

    xil_printf("=== NN done ===\r\n");
    return 0;
}
