/**
 * run_nn.cc — Multi-layer VTA inference, UART interactive loop.
 *
 * Static model data (INSN/UOP/WGT/ACC) must be pre-loaded into DDR via the
 * XSDB script generated by gen_nn_baremetal.py (load_nn.tcl) or embedded in
 * the ELF.  The raw network input is received over UART each iteration.
 *
 * Protocol
 * --------
 *   Board sends: "=== VTA NN runner: <N> step(s) ===\r\n"
 *   Board sends: "input=<N> out=<M>\r\n"
 *   Loop:
 *     Board sends: "READY\r\n"
 *     Host sends:  <input_n_bytes> raw bytes (HWC INT8, no framing)
 *     Board runs inference
 *     Board sends: <out_n_bytes> raw bytes (INT8 from VTA OUT buffer,
 *                  or float bytes if the last step is DEQUANT with no QUANT)
 */

#include "../include/vta_cpu_ops.h"
#include "../include/vta_nn.h"
#include "nn_ddr_map.h"
#include "nn_exec_plan.h"
#include <cstdint>
#include <cstdlib>
extern "C" {
#include "xil_cache.h"
#include "xil_printf.h"
#include "xparameters.h"
}

constexpr std::uintptr_t VTA_VCR_BASE = XPAR_VTA_0_BASEADDR;

// ---------------------------------------------------------------------------
// UART byte I/O
// ---------------------------------------------------------------------------

static void uart_recv(void *dst, std::uint32_t n) {
  auto *p = static_cast<std::uint8_t *>(dst);
  for (std::uint32_t i = 0; i < n; ++i)
    p[i] = inbyte();
}

static void uart_send(const void *src, std::uint32_t n) {
  const auto *p = static_cast<const std::uint8_t *>(src);
  for (std::uint32_t i = 0; i < n; ++i)
    outbyte(p[i]);
}

// ---------------------------------------------------------------------------
// Inference
// ---------------------------------------------------------------------------

// Runs the full execution plan.
// Returns a malloc'd float* when the last output is floating-point (DEQUANT
// not followed by QUANT); *float_bytes is set to the byte count in that case.
// Returns nullptr for INT8 output (read from the VTA OUT buffer directly).
// Sets *ok = false and frees any intermediate allocation on fatal error.
static float *run_inference(std::uint32_t *float_bytes, bool *ok) {
  *ok = true;
  *float_bytes = 0;
  float *float_buf = nullptr;

  for (unsigned i = 0u; i < NN_NUM_STEPS; ++i) {
    const NnExecStep &s = nn_exec_steps[i];
    xil_printf("[vta] step %u/%u: %s\r\n", i, NN_NUM_STEPS - 1u, s.name);

    switch (s.type) {
    case NN_STEP_VTA:
      if (s.vta.layer_idx < 0 ||
          s.vta.layer_idx >= static_cast<int>(NN_NUM_LAYERS)) {
        xil_printf("=== bad layer_idx %d at step %u ===\r\n", s.vta.layer_idx,
                   i);
        std::free(float_buf);
        *ok = false;
        return nullptr;
      }
      if (vta::run_layer(VTA_VCR_BASE, nn_layers[s.vta.layer_idx]) != 0) {
        xil_printf("=== VTA layer failed at step %u ===\r\n", i);
        std::free(float_buf);
        *ok = false;
        return nullptr;
      }
      break;

    case NN_STEP_QADD:
      vta::run_qadd(s.qadd);
      break;

    case NN_STEP_CONCAT:
      vta::run_concat(s.concat);
      break;

    case NN_STEP_DEQUANT:
      float_buf =
          static_cast<float *>(std::malloc(s.dequant.n_elems * sizeof(float)));
      if (!float_buf) {
        xil_printf("=== malloc failed at step %u ===\r\n", i);
        *ok = false;
        return nullptr;
      }
      *float_bytes = s.dequant.n_elems * sizeof(float);
      vta::run_dequant(s.dequant, float_buf);
      break;

    case NN_STEP_QUANT:
      vta::run_quant(s.quant, float_buf);
      std::free(float_buf);
      float_buf = nullptr;
      *float_bytes = 0;
      break;

    case NN_STEP_FORMAT_INPUT:
      vta::run_format_input(s.format_input);
      break;
    }
  }

  return float_buf;
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

int main() {
  xil_printf("=== VTA NN runner: %u step(s) ===\r\n",
             static_cast<unsigned>(NN_NUM_STEPS));

  // Discover raw input location and size from the FORMAT_INPUT step.
  std::uint32_t raw_addr = 0, input_n_bytes = 0;
  for (unsigned i = 0; i < NN_NUM_STEPS; ++i) {
    if (nn_exec_steps[i].type == NN_STEP_FORMAT_INPUT) {
      const auto &fi = nn_exec_steps[i].format_input;
      raw_addr = fi.raw_addr;
      input_n_bytes = fi.tensor_ch * fi.tensor_h * fi.tensor_w;
      break;
    }
  }
  if (input_n_bytes == 0) {
    xil_printf("ERROR: no FORMAT_INPUT step — cannot use UART loop\r\n");
    return -1;
  }

  // Discover INT8 output location from the last VTA step.
  std::uint32_t out_addr = 0, out_n_bytes = 0;
  for (int i = static_cast<int>(NN_NUM_STEPS) - 1; i >= 0; --i) {
    if (nn_exec_steps[i].type == NN_STEP_VTA) {
      const auto &ld = nn_layers[nn_exec_steps[i].vta.layer_idx];
      out_addr = static_cast<std::uint32_t>(ld.out_phys);
      out_n_bytes = static_cast<std::uint32_t>(ld.out_bytes);
      break;
    }
  }

  xil_printf("input=%u out=%u\r\n", input_n_bytes, out_n_bytes);

  while (true) {
    xil_printf("READY\r\n");

    // Receive raw HWC input into scratch DDR, flush cache for PL coherency.
    uart_recv(reinterpret_cast<void *>(raw_addr), input_n_bytes);
    Xil_DCacheFlushRange(raw_addr, input_n_bytes);

    // Run the full inference pipeline.
    std::uint32_t float_bytes = 0;
    bool ok = false;
    float *float_buf = run_inference(&float_bytes, &ok);

    if (!ok) {
      xil_printf("=== inference failed, skipping output ===\r\n");
      continue;
    }

    // OUTPUT sentinel: host reads text lines until this marker, then switches
    // to raw binary receive to avoid mixing log output with payload bytes.
    xil_printf("OUTPUT\r\n");

    // Send output: float buffer if DEQUANT was the last step, INT8 OUT otherwise.
    if (float_buf != nullptr) {
      uart_send(float_buf, float_bytes);
      std::free(float_buf);
    } else {
      uart_send(reinterpret_cast<const void *>(out_addr), out_n_bytes);
    }
  }
}
