version = "3.8.1"
runner.dialect = scala213
preset = IntelliJ
assumeStandardLibraryStripMargin = true
align.stripMargin = true
fileOverride {
  "glob:**/*.mill" {
     runner.dialect = scala3
  }
  "glob:**/out/mill-bsp-out/mill-build/generatedScriptSources.dest/support/**" {
     runner.dialect = scala3
  }
}
