package fpga.synthesis

import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers

class OocNetlistParamsTest extends AnyFlatSpec with Matchers {
  "OocNetlist.renderParams" should "emit the tcl set-lines with the derived clock period" in {
    val out = OocNetlist.renderParams(
      part = "xczu7ev-ffvc1156-2-e",
      svDir = "/emit/vta-debug-xilinx-shell",
      top = "VTAXilinxShell",
      outDir = "/run/ooc-netlist",
      projDir = "/run/ooc-netlist/proj",
      clkPort = "ap_clk",
      plClockMhz = "100", // -> 10.0 ns
      mode = "synth",
      jobs = 8
    )
    out shouldBe
      """# auto-generated by fpga.synthesis.OocNetlist - do not edit
        |set part          xczu7ev-ffvc1156-2-e
        |set sv_dir        /emit/vta-debug-xilinx-shell
        |set top           VTAXilinxShell
        |set out_dir       /run/ooc-netlist
        |set proj_dir      /run/ooc-netlist/proj
        |set clk_port      ap_clk
        |set clk_period_ns 10.0
        |set mode          synth
        |set jobs          8
        |""".stripMargin
  }
}
