version = "3.10.4"
runner.dialect = scala213
fileOverride {
  "glob:**/build.mill/**" {
     runner.dialect = scala3
  }
  "glob:**/out/mill-bsp-out/mill-build/generatedScriptSources.dest/support/**" {
     runner.dialect = scala3
  }
  preset=IntelliJ
  assumeStandardLibraryStripMargin=true
  align.stripMargin = true
}
