"""VTA hardware config parsing and the generated vta_hw_config.h."""

import json
import sys
from dataclasses import dataclass
from typing import Optional

DEFAULT_BLOCK_SIZE = 16  # Config default; override with --config-json or --block-size
DEFAULT_LOG_INP_WIDTH = 5  # 32-bit (reference config)
DEFAULT_LOG_OUT_WIDTH = 5
DEFAULT_LOG_WGT_WIDTH = 5
DEFAULT_LOG_ACC_WIDTH = 5
@dataclass
class ConfigParams:
    block_size: int  # 1 << LOG_BLOCK
    log_inp_width: int  # LOG_INP_WIDTH (raw log value)
    log_out_width: int  # LOG_OUT_WIDTH
    log_wgt_width: int  # LOG_WGT_WIDTH
    log_acc_width: int  # LOG_ACC_WIDTH
    target: Optional[str] = None  # config "TARGET"; the Xilinx IP is named VTA_<TARGET>
def load_config_params(
    config_json_path: Optional[str], cli_block_size: Optional[int]
) -> ConfigParams:
    """Load hardware config parameters from JSON and/or CLI overrides.

    Priority for block_size: explicit --block-size > --config-json LOG_BLOCK > default.
    Width fields always come from --config-json (defaulting to 32-bit if absent).
    """
    log_inp = DEFAULT_LOG_INP_WIDTH
    log_out = DEFAULT_LOG_OUT_WIDTH
    log_wgt = DEFAULT_LOG_WGT_WIDTH
    log_acc = DEFAULT_LOG_ACC_WIDTH
    block_size = DEFAULT_BLOCK_SIZE
    target: Optional[str] = None

    if config_json_path:
        try:
            with open(config_json_path) as f:
                cfg = json.load(f)

            target = cfg.get("TARGET")
            log_block = cfg.get("LOG_BLOCK")
            if log_block is not None:
                block_size = 1 << int(log_block)
            else:
                print(
                    f"WARNING: LOG_BLOCK not found in {config_json_path}"
                    f" - using default {DEFAULT_BLOCK_SIZE}"
                )

            for key, default, dest in [
                ("LOG_INP_WIDTH", DEFAULT_LOG_INP_WIDTH, "log_inp"),
                ("LOG_OUT_WIDTH", DEFAULT_LOG_OUT_WIDTH, "log_out"),
                ("LOG_WGT_WIDTH", DEFAULT_LOG_WGT_WIDTH, "log_wgt"),
                ("LOG_ACC_WIDTH", DEFAULT_LOG_ACC_WIDTH, "log_acc"),
            ]:
                val = cfg.get(key)
                if val is None:
                    print(
                        f"WARNING: {key} not found in {config_json_path}"
                        f" - using default {default}"
                    )
                else:
                    if dest == "log_inp":
                        log_inp = int(val)
                    elif dest == "log_out":
                        log_out = int(val)
                    elif dest == "log_wgt":
                        log_wgt = int(val)
                    elif dest == "log_acc":
                        log_acc = int(val)

        except Exception as e:
            print(f"WARNING: could not read {config_json_path}: {e} - using defaults")

    if cli_block_size is not None:
        block_size = cli_block_size

    return ConfigParams(
        block_size=block_size,
        log_inp_width=log_inp,
        log_out_width=log_out,
        log_wgt_width=log_wgt,
        log_acc_width=log_acc,
        target=target,
    )
def _ctype_from_log_width(log_width: int) -> str:
    bits = 1 << log_width
    return {8: "std::int8_t", 16: "std::int16_t", 32: "std::int32_t"}.get(
        bits, f"/* unsupported {bits}-bit */"
    )
def _elem_bytes(log_width: int) -> int:
    """Bytes per element for a buffer of width 2**log_width bits (LOG_*_WIDTH).

    Single source of truth for element-width derivation, so byte<->element
    conversions stay correct across VTA configs (e.g. int8 INP/OUT vs int32).
    """
    return (1 << log_width) // 8
def gen_hw_config_header(cfg: ConfigParams, path: str) -> None:
    """Generate vta_hw_config.h with type aliases derived from the hardware config."""
    inp_t = _ctype_from_log_width(cfg.log_inp_width)
    out_t = _ctype_from_log_width(cfg.log_out_width)
    acc_t = _ctype_from_log_width(cfg.log_acc_width)
    wgt_t = _ctype_from_log_width(cfg.log_wgt_width)
    lines = [
        "#pragma once",
        "// Generated by gen_nn_baremetal.py - Do not edit manually.",
        f"// LOG_INP_WIDTH={cfg.log_inp_width}, LOG_OUT_WIDTH={cfg.log_out_width},"
        f" LOG_WGT_WIDTH={cfg.log_wgt_width}, LOG_ACC_WIDTH={cfg.log_acc_width},"
        f" LOG_BLOCK={cfg.block_size.bit_length() - 1}",
        "#include <cstdint>",
        "#include <limits>",
        'extern "C" {',
        '#include "xparameters.h"',
        "}",
        # The VTA control base macro name depends on how the BSP names the IP.
        # The Vitis SDT flow derives it from the IP display name "VTA_<TARGET>"
        # (e.g. TARGET=foo -> peripheral VTA_FOO_0 -> XPAR_VTA_FOO_0_BASEADDR);
        # older/classic BSPs may expose XPAR_VTA_0_BASEADDR. Try the target-specific
        # name first, then the generic one, and fail clearly if neither exists.
        *(
            [f"#if defined(XPAR_VTA_{cfg.target.upper()}_0_BASEADDR)",
             f"#define VTA_VCR_BASE_ADDR XPAR_VTA_{cfg.target.upper()}_0_BASEADDR",
             "#elif defined(XPAR_VTA_0_BASEADDR)"]
            if cfg.target
            else ["#if defined(XPAR_VTA_0_BASEADDR)"]
        ),
        "#define VTA_VCR_BASE_ADDR XPAR_VTA_0_BASEADDR",
        "#else",
        '#error "VTA control base address not found in xparameters.h '
        '(expected XPAR_VTA_<TARGET>_0_BASEADDR or XPAR_VTA_0_BASEADDR)"',
        "#endif",
        "static constexpr std::uintptr_t VTA_VCR_BASE = VTA_VCR_BASE_ADDR;",
        f"using vta_inp_t = {inp_t};",
        f"using vta_out_t = {out_t};",
        f"using vta_acc_t = {acc_t};",
        f"using vta_wgt_t = {wgt_t};",
        f"constexpr int VTA_BLOCK_SIZE = {cfg.block_size};",
        "constexpr std::int64_t VTA_OUT_MIN = std::numeric_limits<vta_out_t>::min();",
        "constexpr std::int64_t VTA_OUT_MAX = std::numeric_limits<vta_out_t>::max();",
    ]
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"[gen] {path}")
def check_config_compat(cfg: ConfigParams, dep_info: "DependencyInfo") -> None:
    """Emit warnings/errors for known FPGA software incompatibilities."""
    if cfg.log_inp_width == 3 or cfg.log_out_width == 3:
        print(
            f"WARNING: 8-bit data width detected"
            f" (LOG_INP_WIDTH={cfg.log_inp_width}, LOG_OUT_WIDTH={cfg.log_out_width})."
            f" CPU ops will use int8_t."
            f" Ensure compiler output and network quantization are 8-bit."
        )

    # This stack requantizes on the CPU (run_rescale / fsim step-E rescaling),
    # which reads the VTA OUT region as the pre-rescale value.  The VTA store
    # (TruncStore) truncates the int32 accumulator to the OUT width with no
    # shift, so OUT must be as wide as ACC or the accumulator is destroyed
    # before requant.  The generator also only emits the NN_STEP_RESCALE when
    # log_out_width > 3, so a narrow OUT silently drops the per-layer scale that
    # fsim always applies.  Refuse such a config when any layer actually needs a
    # requant (non-unit scale or non-zero output zero-point).
    requant_layers = [
        name
        for _, processor, name in dep_info.execution_order
        if processor == "vta"
        and (ld := dep_info.layers.get(name)) is not None
        and (abs(ld.scale - 1.0) > 1e-9 or ld.offset_c != 0)
    ]
    if cfg.log_out_width < cfg.log_acc_width and requant_layers:
        sys.exit(
            f"ERROR: LOG_OUT_WIDTH={cfg.log_out_width} < LOG_ACC_WIDTH="
            f"{cfg.log_acc_width} but {len(requant_layers)} layer(s) need CPU"
            f" requantization (e.g. '{requant_layers[0]}'). This stack truncates"
            f" the int32 accumulator to the OUT width in the store (no shift) and"
            f" rescales on the CPU, so QLinear requant needs OUT as wide as ACC"
            f" (int32). Use a config with LOG_OUT_WIDTH=LOG_ACC_WIDTH, or add"
            f" store-side requantization."
        )

    for _, processor, layer_name in dep_info.execution_order:
        ld = dep_info.layers.get(layer_name)
        if ld is None:
            continue

        if processor == "vta" and ld.reshape_info == "im2row" and ld.sh != ld.sw:
            print(
                f"WARNING: layer '{layer_name}' uses asymmetric strides"
                f" (sh={ld.sh}, sw={ld.sw})."
                f" The functional simulator im2row() only supports isotropic stride;"
                f" simulation results will differ from FPGA execution."
            )

        if processor == "concat" and ld.nb_inp > 4:
            sys.exit(
                f"ERROR: concat layer '{layer_name}' has {ld.nb_inp} inputs;"
                f" NnConcatStep supports at most 4."
            )
