"""Emitters for the C headers (nn_ddr_map.h, nn_exec_plan.h)."""

import csv
from typing import Dict, List, Optional

from .config import DEFAULT_BLOCK_SIZE, _elem_bytes
from .model import DependencyInfo, LayerInfo, hex32, insn_count_from_file
from .layout import _build_cpu_out_addrs, _cpu_out_addr, _out_addr, scratch_addr


def gen_header(layers: List[LayerInfo], ddr_base: int, out_path: str) -> None:
    L: List[str] = []
    L.append("/* Auto-generated by host/gen_nn_baremetal.py - DO NOT EDIT */")
    L.append("#pragma once")
    L.append('#include "vta_nn.h"')
    L.append("")
    L.append(f"#define DDR_NN_BASE   {hex32(ddr_base)}")
    L.append(f"#define NN_NUM_LAYERS {len(layers)}")
    L.append("")
    L.append("static const vta::LayerDesc nn_layers[NN_NUM_LAYERS] = {")

    for i, layer in enumerate(layers):
        m = layer.mem
        insn_count = insn_count_from_file(layer.bin_files["INSN"], m["INSN"].size)
        L.append(f'    /* layer {i}  suffix="{layer.suffix}" */')
        L.append("    {")
        L.append(f"        .ddr_base    = {hex32(ddr_base)},")
        L.append(f"        .insn_addr   = {hex32(ddr_base + m['INSN'].offset)},")
        L.append(f"        .insn_count  = {insn_count}u,")
        L.append(f"        .uop_phys    = {hex32(ddr_base + m['UOP'].offset)},")
        L.append(f"        .uop_bytes   = {hex32(m['UOP'].size)},")
        L.append(f"        .inp_phys    = {hex32(ddr_base + m['INP'].offset)},")
        L.append(f"        .inp_bytes   = {hex32(m['INP'].size)},")
        L.append(f"        .wgt_phys    = {hex32(ddr_base + m['WGT'].offset)},")
        L.append(f"        .wgt_bytes   = {hex32(m['WGT'].size)},")
        L.append(f"        .acc_phys    = {hex32(ddr_base + m['ACC'].offset)},")
        L.append(f"        .acc_bytes   = {hex32(m['ACC'].size)},")
        L.append(f"        .out_phys    = {hex32(ddr_base + m['OUT'].offset)},")
        L.append(f"        .out_bytes   = {hex32(m['OUT'].size)},")
        L.append(f"    }}" + ("," if i < len(layers) - 1 else ""))

    L.append("};")
    L.append("")
    with open(out_path, "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"[gen] C header written to {out_path}")


def gen_exec_plan_header(
    dep_info: DependencyInfo,
    layers: List[LayerInfo],
    ddr_base: int,
    comp_dir: str,
    out_path: str,
    block_size: int = DEFAULT_BLOCK_SIZE,
    suffix_to_idx: Optional[Dict[str, int]] = None,
    cpu_out: Optional[Dict[str, int]] = None,
    log_out_width: int = 3,
    ct_params: Optional[Dict[str, Dict[str, int]]] = None,
) -> None:
    if suffix_to_idx is None:
        suffix_to_idx = {layer.suffix: i for i, layer in enumerate(layers)}
    if cpu_out is None:
        cpu_out, _, _ = _build_cpu_out_addrs(
            dep_info, layers, ddr_base, suffix_to_idx, comp_dir
        )
    num_steps = len(dep_info.execution_order)

    # Resolve the true final network output address.
    # dep_info.output_layer is the layer name from the "output" row in dependency.csv.
    output_name = dep_info.output_layer
    out_idx = suffix_to_idx.get(output_name, -1)
    if out_idx >= 0:
        # VTA final layer: output is in its OUT buffer.
        # After run_rescale() the buffer holds int8_t in-place, so the true
        # output size is out_size / (vta_out_t width in bytes).
        nn_output_addr = ddr_base + layers[out_idx].mem["OUT"].offset
        out_size = layers[out_idx].mem["OUT"].size
        if log_out_width > 3:
            nn_output_bytes = out_size // _elem_bytes(log_out_width)
        else:
            nn_output_bytes = out_size
    else:
        # CPU final layer (concat, qadd, quant, ...): output is in the cpu_out scratch
        nn_output_addr = cpu_out.get(output_name, 0) if cpu_out else 0
        ld_out = dep_info.layers.get(output_name)
        nn_output_bytes = (ld_out.out_ch * ld_out.out_h * ld_out.out_w) if ld_out else 0
    if nn_output_addr == 0:
        print(
            f"WARNING: could not resolve NN_OUTPUT_ADDR for output layer '{output_name}'"
        )

    L: List[str] = []
    L.append("/* Auto-generated by host/gen_nn_baremetal.py - DO NOT EDIT */")
    L.append("#pragma once")
    L.append('#include "vta_nn.h"')
    L.append("")
    L.append("/* Final network output location */")
    L.append(f"#define NN_OUTPUT_ADDR  {hex32(nn_output_addr)}")
    L.append(f"#define NN_OUTPUT_BYTES {nn_output_bytes}u")
    L.append("")

    # Build reshape steps for all VTA layers with reshape_info == "im2row".
    # Two sub-cases:
    #   deps[0] == "image" -> NN_STEP_FORMAT_INPUT (reads HWC-flat raw image)
    #   deps[0] != "image" -> NN_STEP_IM2ROW       (reads VTA block-tiled OUT)
    # Maps: layer_name -> step params dict
    format_input_steps: Dict[str, Dict] = {}
    im2row_steps: Dict[str, Dict] = {}
    raw_phys = scratch_addr(layers, ddr_base)
    for _, processor, layer_name in dep_info.execution_order:
        if processor != "vta":
            continue
        ld = dep_info.layers.get(layer_name)
        if not ld or ld.reshape_info != "im2row":
            continue
        idx = suffix_to_idx.get(layer_name, -1)
        if idx < 0:
            continue
        out_h = (ld.tensor_h + ld.pad[0] + ld.pad[2] - ld.kh) // ld.sh + 1
        out_w = (ld.tensor_w + ld.pad[1] + ld.pad[3] - ld.kw) // ld.sw + 1
        common = {
            "inp_addr": ddr_base + layers[idx].mem["INP"].offset,
            "tensor_ch": ld.tensor_ch,
            "tensor_h": ld.tensor_h,
            "tensor_w": ld.tensor_w,
            "kh": ld.kh,
            "kw": ld.kw,
            "sh": ld.sh,
            "sw": ld.sw,
            "pad": ld.pad,
            "offset_a": ld.offset_a,
            "out_h": out_h,
            "out_w": out_w,
        }
        if ld.deps and ld.deps[0] == "image":
            format_input_steps[layer_name] = {**common, "raw_addr": raw_phys}
        else:
            dep_name = ld.deps[0] if ld.deps else ""
            src = _out_addr(
                dep_name, dep_info, layers, ddr_base, suffix_to_idx, cpu_out
            )
            if src == 0:
                print(
                    f"WARNING: im2row source address for '{layer_name}' dep '{dep_name}' resolved to 0"
                )
            im2row_steps[layer_name] = {**common, "src_addr": src}

    # Build int32-chain steps for VTA layers with reshape_info == "int32"
    # (maxpool / direct-ACC).  Their input lives entirely in ACC and is the
    # producer's (post-rescale int8) OUT widened to int32 - the runtime
    # equivalent of fsim_nn.cc's convert_vector_type<acc> + subtract_offset.
    int32_chain_steps: Dict[str, Dict] = {}
    for _, processor, layer_name in dep_info.execution_order:
        if processor != "vta":
            continue
        ld = dep_info.layers.get(layer_name)
        if not ld or ld.reshape_info != "int32":
            continue
        idx = suffix_to_idx.get(layer_name, -1)
        if idx < 0:
            continue
        acc = layers[idx].mem["ACC"]
        if acc.size == 0:
            print(f"WARNING: int32 layer '{layer_name}' has no ACC - chain skipped")
            continue
        dep_name = ld.deps[0] if ld.deps else ""
        src = _out_addr(dep_name, dep_info, layers, ddr_base, suffix_to_idx, cpu_out)
        if src == 0:
            print(
                f"WARNING: int32-chain source for '{layer_name}' dep '{dep_name}'"
                f" resolved to 0"
            )

        # Output element count in VTA block layout.  Both dims round up to a
        # block multiple: the producer (a GEMM/conv) writes its OUT block-tiled
        # (spatial N padded to ceil(N/B)*B) and channels are padded to
        # ceil(C/B)*B, and fsim's pad_matrix (isSquare) pads the same way.  Raw
        # tensor_ch*h*w under-counts and leaves block-pad slots unwritten.
        # Spatial padding (pad != 0) grows H/W first, mirroring fsim pad_matrix.
        def _ru(x: int) -> int:
            return ((x + block_size - 1) // block_size) * block_size

        out_h = ld.tensor_h + ld.pad[0] + ld.pad[2]
        out_w = ld.tensor_w + ld.pad[1] + ld.pad[3]
        n_elems_blocked = _ru(out_h * out_w) * _ru(ld.tensor_ch)
        int32_chain_steps[layer_name] = {
            "src_addr": src,  # producer OUT (compact int8 after its RESCALE)
            "dst_addr": ddr_base + acc.offset,  # this layer's ACC
            "n_elems": n_elems_blocked,  # output count (block-padded both dims)
            "offset_a": ld.offset_a,
            "pad": ld.pad,
            "tensor_ch": ld.tensor_ch,
            "tensor_h": ld.tensor_h,
            "tensor_w": ld.tensor_w,
        }

    # Inter-layer activations are compact int8 in every config: when OUT is
    # wider than int8 (log_out_width > 3) a CPU RESCALE step quantizes int32->int8
    # in place; when OUT is already int8 (log_out_width == 3) the VTA store does
    # the quantization, so no rescale step is needed.  Downstream consumers
    # (im2row / int32_chain / qadd / ...) therefore always read int8.
    n_rescale_steps = (
        sum(1 for _, p, _ in dep_info.execution_order if p == "vta")
        if log_out_width > 3
        else 0
    )
    extra = (
        len(format_input_steps)
        + len(im2row_steps)
        + len(int32_chain_steps)
        + n_rescale_steps
    )
    total_steps = num_steps + extra

    L += [
        f"#define NN_NUM_STEPS {total_steps}u",
        "",
        "static const struct NnExecStep nn_exec_steps[NN_NUM_STEPS] = {",
    ]

    emitted = 0  # count of entries written so far (for trailing comma logic)

    def _comma(pos: int) -> str:
        return "," if pos < total_steps - 1 else ""

    for k, (step_idx, processor, layer_name) in enumerate(dep_info.execution_order):
        ld = dep_info.layers.get(layer_name)

        # Inject FORMAT_INPUT step before first VTA layer that reads raw image
        if processor == "vta" and layer_name in format_input_steps:
            fi = format_input_steps[layer_name]
            L.append(f"    /* format_input for {layer_name} */")
            L.append(
                f'    {{ NN_STEP_FORMAT_INPUT, "format_{layer_name}", {{ .format_input = {{'
            )
            L.append(f"        {hex32(fi['raw_addr'])}, {hex32(fi['inp_addr'])},")
            L.append(
                f"        {fi['tensor_ch']}u, {fi['tensor_h']}u, {fi['tensor_w']}u,"
            )
            L.append(f"        {fi['kh']}u, {fi['kw']}u, {fi['sh']}u, {fi['sw']}u,")
            L.append(
                f"        {{ {fi['pad'][0]}, {fi['pad'][1]}, {fi['pad'][2]}, {fi['pad'][3]} }},"
            )
            L.append(f"        {fi['offset_a']},")
            L.append(f"        {fi['out_h']}u, {fi['out_w']}u, {block_size}u")
            L.append(f"    }} }} }},")
            emitted += 1

        # Inject IM2ROW step before any VTA layer that reads a previous layer's OUT
        elif processor == "vta" and layer_name in im2row_steps:
            ir = im2row_steps[layer_name]
            L.append(f"    /* im2row for {layer_name} */")
            L.append(f'    {{ NN_STEP_IM2ROW, "im2row_{layer_name}", {{ .im2row = {{')
            L.append(f"        {hex32(ir['src_addr'])}, {hex32(ir['inp_addr'])},")
            L.append(
                f"        {ir['tensor_ch']}u, {ir['tensor_h']}u, {ir['tensor_w']}u,"
            )
            L.append(f"        {ir['kh']}u, {ir['kw']}u, {ir['sh']}u, {ir['sw']}u,")
            L.append(
                f"        {{ {ir['pad'][0]}, {ir['pad'][1]}, {ir['pad'][2]}, {ir['pad'][3]} }},"
            )
            L.append(f"        {ir['offset_a']},")
            L.append(f"        {ir['out_h']}u, {ir['out_w']}u, {block_size}u")
            L.append(f"    }} }} }},")
            emitted += 1

        # Inject INT32_CHAIN step before any int32/maxpool VTA layer: widen the
        # producer's (post-rescale int8) OUT into this layer's ACC.
        elif processor == "vta" and layer_name in int32_chain_steps:
            ic = int32_chain_steps[layer_name]
            L.append(f"    /* int32 chain for {layer_name} */")
            L.append(
                f'    {{ NN_STEP_INT32_CHAIN, "int32_chain_{layer_name}",'
                f" {{ .int32_chain = {{"
            )
            L.append(f"        {hex32(ic['src_addr'])}, {hex32(ic['dst_addr'])},")
            L.append(f"        {ic['n_elems']}u, {ic['offset_a']},")
            L.append(
                f"        {{ {ic['pad'][0]}, {ic['pad'][1]}, {ic['pad'][2]}, {ic['pad'][3]} }},"
            )
            L.append(
                f"        {ic['tensor_ch']}u, {ic['tensor_h']}u, {ic['tensor_w']}u"
            )
            L.append(f"    }} }} }},")
            emitted += 1

        if processor == "vta":
            vta_idx = suffix_to_idx.get(layer_name, -1)
            if vta_idx < 0:
                print(f"WARNING: VTA layer '{layer_name}' not found in layers list")
            L.append(f"    /* step {step_idx} */")
            L.append(
                f'    {{ NN_STEP_VTA, "{layer_name}", {{ .vta = {{ {vta_idx} }} }} }}{_comma(emitted)}'
            )
            emitted += 1
            if log_out_width > 3 and vta_idx >= 0 and ld is not None:
                out_bytes = layers[vta_idx].mem["OUT"].size
                n_elems = out_bytes // _elem_bytes(log_out_width)
                out_addr = ddr_base + layers[vta_idx].mem["OUT"].offset
                L.append(f"    /* step {step_idx} rescale */")
                L.append(
                    f'    {{ NN_STEP_RESCALE, "{layer_name}_rescale", '
                    f"{{ .rescale = {{ {hex32(out_addr)}, {n_elems}u, "
                    f"{ld.scale}f, {ld.offset_c} }} }} }}{_comma(emitted)}"
                )
                emitted += 1

        elif processor == "qadd" and ld:
            inpA = _out_addr(
                ld.deps[0] if ld.deps else "",
                dep_info,
                layers,
                ddr_base,
                suffix_to_idx,
                cpu_out,
            )
            inpB = _out_addr(
                ld.deps[1] if len(ld.deps) > 1 else "",
                dep_info,
                layers,
                ddr_base,
                suffix_to_idx,
                cpu_out,
            )
            out = _cpu_out_addr(
                layer_name, dep_info, layers, ddr_base, suffix_to_idx, k + 1, cpu_out
            )
            n = ld.out_ch * ld.out_h * ld.out_w
            L.append(f"    /* step {step_idx}: qadd */")
            L.append(f'    {{ NN_STEP_QADD, "{layer_name}", {{ .qadd = {{')
            L.append(f"        {hex32(inpA)}, {hex32(inpB)}, {hex32(out)}, {n}u,")
            L.append(f"        {ld.scale_a}f, {ld.scale_b}f, {ld.scale_c}f,")
            L.append(f"        {ld.offset_a}, {ld.offset_b}, {ld.offset_c}")
            L.append(f"    }} }} }}{_comma(emitted)}")
            emitted += 1

        elif processor == "concat" and ld:
            inp_addrs = [
                _out_addr(
                    ld.deps[j] if j < len(ld.deps) else "",
                    dep_info,
                    layers,
                    ddr_base,
                    suffix_to_idx,
                    cpu_out,
                )
                for j in range(4)
            ]
            out = _cpu_out_addr(
                layer_name, dep_info, layers, ddr_base, suffix_to_idx, k + 1, cpu_out
            )
            n_rows = ld.tensor_h * ld.tensor_w
            n_ch_per_inp = ld.tensor_ch
            L.append(f"    /* step {step_idx}: concat */")
            L.append(f'    {{ NN_STEP_CONCAT, "{layer_name}", {{ .concat = {{')
            L.append(f"        {{ {', '.join(hex32(a) for a in inp_addrs)} }},")
            L.append(f"        {hex32(out)}, {n_rows}u, {n_ch_per_inp}u, {ld.nb_inp},")
            L.append(
                f"        {{ {ld.scale_a}f, {ld.scale_b}f, {ld.scale_u}f, {ld.scale_v}f }},"
            )
            L.append(
                f"        {{ {ld.offset_a}, {ld.offset_b}, {ld.offset_u}, {ld.offset_v} }},"
            )
            L.append(f"        {ld.scale_c}f, {ld.offset_c}, {block_size}u")
            L.append(f"    }} }} }}{_comma(emitted)}")
            emitted += 1

        elif processor == "dequant" and ld:
            inp = _out_addr(
                ld.deps[0] if ld.deps else "",
                dep_info,
                layers,
                ddr_base,
                suffix_to_idx,
                cpu_out,
            )
            n = ld.tensor_ch * ld.tensor_h * ld.tensor_w
            L.append(f"    /* step {step_idx}: dequant */")
            L.append(f'    {{ NN_STEP_DEQUANT, "{layer_name}", {{ .dequant = {{')
            L.append(f"        {hex32(inp)}, {n}u, {ld.scale_a}f, {ld.offset_a}")
            L.append(f"    }} }} }}{_comma(emitted)}")
            emitted += 1

        elif processor == "quant" and ld:
            out = _cpu_out_addr(
                layer_name, dep_info, layers, ddr_base, suffix_to_idx, k + 1, cpu_out
            )
            n = ld.out_ch * ld.out_h * ld.out_w
            L.append(f"    /* step {step_idx}: quant */")
            L.append(f'    {{ NN_STEP_QUANT, "{layer_name}", {{ .quant = {{')
            L.append(f"        {hex32(out)}, {n}u, {ld.scale_a}f, {ld.offset_a}")
            L.append(f"    }} }} }}{_comma(emitted)}")
            emitted += 1

        elif processor == "convtranspose" and ld:
            p = (ct_params or {}).get(layer_name)
            if not p:
                print(
                    f"WARNING: convtranspose '{layer_name}' has no param allocation"
                    " - emitting VTA stub"
                )
                L.append(
                    f"    /* step {step_idx}: convtranspose {layer_name} - no params */"
                )
                L.append(
                    f'    {{ NN_STEP_VTA, "{layer_name}", {{ .vta = {{ -1 }} }} }}{_comma(emitted)}'
                )
                emitted += 1
            else:
                # Output count in block-tiled layout (both dims padded to a block
                # multiple, like fsim's data_formatting); the next quant step reads
                # this float_buf.  Input/output are the runtime float_buf, so no
                # DDR in/out address is emitted - only the param blob addresses.
                def _ru(x: int) -> int:
                    return ((x + block_size - 1) // block_size) * block_size

                n_out = _ru(ld.out_h * ld.out_w) * _ru(ld.out_ch)
                L.append(f"    /* step {step_idx}: convtranspose */")
                L.append(
                    f'    {{ NN_STEP_CONVTRANSPOSE, "{layer_name}",'
                    f" {{ .convtranspose = {{"
                )
                L.append(
                    f"        {hex32(p['wgt_addr'])}, {hex32(p['bias_addr'])},"
                    f" {p['has_bias']}u,"
                )
                L.append(f"        {ld.tensor_ch}u, {ld.tensor_h}u, {ld.tensor_w}u,")
                L.append(f"        {ld.out_ch}u, {ld.out_h}u, {ld.out_w}u,")
                # Single stride (fsim conv_transpose is scalar-stride; sh==sw).
                L.append(f"        {ld.kh}u, {ld.kw}u, {ld.sh}u,")
                L.append(
                    f"        {{ {ld.pad[0]}, {ld.pad[1]}, {ld.pad[2]}, {ld.pad[3]} }},"
                )
                L.append(f"        {block_size}u, {n_out}u")
                L.append(f"    }} }} }}{_comma(emitted)}")
                emitted += 1

        else:
            print(
                f"WARNING: unsupported processor '{processor}' for '{layer_name}' - emitting VTA stub"
            )
            L.append(
                f"    /* step {step_idx}: {processor} {layer_name} - unsupported, skipped */"
            )
            L.append(
                f'    {{ NN_STEP_VTA, "{layer_name}", {{ .vta = {{ -1 }} }} }}{_comma(emitted)}'
            )
            emitted += 1

    L.append("};")
    L.append("")
    with open(out_path, "w") as f:
        f.write("\n".join(L) + "\n")
    print(
        f"[gen] Exec plan written to {out_path} ({total_steps} steps, "
        f"{len(format_input_steps)} format-input, {len(im2row_steps)} im2row, "
        f"{n_rescale_steps} rescale)"
    )
