/* Auto-generated by the VTA baremetal codegen - DO NOT EDIT */
#pragma once
#include "vta_nn_debug.h"

#define NN_NUM_DEBUG 7

static const vta::DebugLayerDesc nn_debug[NN_NUM_DEBUG] = {
    /* layer 0  suffix="QLinearConv1" */
    {
        .layer_idx     = 0u,
        .in_ref_phys   = 0x000C9000u,
        .in_ref_bytes  = 0x00018800u,
        .in_dst_phys   = 0x0001C000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearConv1",
    },
    /* layer 1  suffix="MaxPool2" */
    {
        .layer_idx     = 1u,
        .in_ref_phys   = 0x000E2000u,
        .in_ref_bytes  = 0x00000000u,
        .in_dst_phys   = 0x00001000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "MaxPool2",
    },
    /* layer 2  suffix="QLinearConv3" */
    {
        .layer_idx     = 2u,
        .in_ref_phys   = 0x000E2000u,
        .in_ref_bytes  = 0x00011800u,
        .in_dst_phys   = 0x00052000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearConv3",
    },
    /* layer 3  suffix="MaxPool4" */
    {
        .layer_idx     = 3u,
        .in_ref_phys   = 0x000F4000u,
        .in_ref_bytes  = 0x00000000u,
        .in_dst_phys   = 0x00017000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "MaxPool4",
    },
    /* layer 4  suffix="QLinearConv5" */
    {
        .layer_idx     = 4u,
        .in_ref_phys   = 0x000F4000u,
        .in_ref_bytes  = 0x00006400u,
        .in_dst_phys   = 0x0006D000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearConv5",
    },
    /* layer 5  suffix="QLinearConv6" */
    {
        .layer_idx     = 5u,
        .in_ref_phys   = 0x000FB000u,
        .in_ref_bytes  = 0x00002000u,
        .in_dst_phys   = 0x000AC000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearConv6",
    },
    /* layer 6  suffix="QLinearConv7" */
    {
        .layer_idx     = 6u,
        .in_ref_phys   = 0x000FD000u,
        .in_ref_bytes  = 0x00001800u,
        .in_dst_phys   = 0x000C0000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearConv7",
    }
};

