/* Auto-generated by gen_nn_baremetal.py - DO NOT EDIT */
#pragma once
#include "vta_cpu_ops_debug.h"

/*
 * Coverage: only CPU ops whose output buffer equals a VTA layer's
 * golden INP/ACC dump are checked (FORMAT_INPUT / IM2ROW / INT32_CHAIN).
 * Other CPU ops (rescale / qadd / concat / dequant / quant) are
 * absent from the table and silently skipped at runtime.
 *
 * Isolation-mode source fields (src_ref_*, src_dst_phys) preload each
 * op's INPUT with a known-good golden (raw image for format_input, the
 * producer layer's pre-rescale out_ref for im2row/int32_chain) so a bad
 * upstream layer does not cascade.  The runtime replays the producer
 * rescale before the reshape.  Entries left at 0 (no embedded golden,
 * e.g. --emit-layer-check not run) fall back to the preloaded buffer.
 *
 * Skipped at codegen:
 *   - format_QLinearConv1 (no upstream golden - isolation fallback)
 *   - im2row_QLinearConv2 (no upstream golden - isolation fallback)
 *   - im2row_QLinearConv3 (no upstream golden - isolation fallback)
 *   - im2row_QLinearConv4 (no upstream golden - isolation fallback)
 *   - im2row_QLinearMul5 (no upstream golden - isolation fallback)
 *   - im2row_QLinearConv6 (no upstream golden - isolation fallback)
 *   - im2row_QLinearConv8 (no upstream golden - isolation fallback)
 *   - im2row_QLinearMul9 (no upstream golden - isolation fallback)
 *   - im2row_QLinearConv10 (no upstream golden - isolation fallback)
 */

#define NN_NUM_CPU_DEBUG 9u

static const vta::DebugCpuStep nn_cpu_debug[NN_NUM_CPU_DEBUG] = {
    /* format_input */
    {
        .step_idx      = 0u,
        .out_phys      = 0x00001000u,
        .out_bytes     = 0x02A30000u,
        .ref_phys      = 0x10113000u,
        .ref_bytes     = 0x02A30000u,
        .elem_bytes    = std::uint16_t(4u),
        ._pad          = std::uint16_t(0u),
        .src_ref_phys  = 0x00000000u,
        .src_ref_bytes = 0x00000000u,
        .src_dst_phys  = 0x00000000u,
        .name          = "format_QLinearConv1",
    },
    /* im2row */
    {
        .step_idx      = 3u,
        .out_phys      = 0x06211000u,
        .out_bytes     = 0x00960000u,
        .ref_phys      = 0x12B43000u,
        .ref_bytes     = 0x00960000u,
        .elem_bytes    = std::uint16_t(4u),
        ._pad          = std::uint16_t(0u),
        .src_ref_phys  = 0x00000000u,
        .src_ref_bytes = 0x00000000u,
        .src_dst_phys  = 0x00000000u,
        .name          = "im2row_QLinearConv2",
    },
    /* im2row */
    {
        .step_idx      = 6u,
        .out_phys      = 0x071D8000u,
        .out_bytes     = 0x00960000u,
        .ref_phys      = 0x134A3000u,
        .ref_bytes     = 0x00960000u,
        .elem_bytes    = std::uint16_t(4u),
        ._pad          = std::uint16_t(0u),
        .src_ref_phys  = 0x00000000u,
        .src_ref_bytes = 0x00000000u,
        .src_dst_phys  = 0x00000000u,
        .name          = "im2row_QLinearConv3",
    },
    /* im2row */
    {
        .step_idx      = 9u,
        .out_phys      = 0x0819F000u,
        .out_bytes     = 0x01C20000u,
        .ref_phys      = 0x13E03000u,
        .ref_bytes     = 0x01C20000u,
        .elem_bytes    = std::uint16_t(4u),
        ._pad          = std::uint16_t(0u),
        .src_ref_phys  = 0x00000000u,
        .src_ref_bytes = 0x00000000u,
        .src_dst_phys  = 0x00000000u,
        .name          = "im2row_QLinearConv4",
    },
    /* im2row */
    {
        .step_idx      = 12u,
        .out_phys      = 0x0EB0E000u,
        .out_bytes     = 0x00320000u,
        .ref_phys      = 0x15A23000u,
        .ref_bytes     = 0x00320000u,
        .elem_bytes    = std::uint16_t(4u),
        ._pad          = std::uint16_t(0u),
        .src_ref_phys  = 0x00000000u,
        .src_ref_bytes = 0x00000000u,
        .src_dst_phys  = 0x00000000u,
        .name          = "im2row_QLinearMul5",
    },
    /* im2row */
    {
        .step_idx      = 15u,
        .out_phys      = 0x0A4C4000u,
        .out_bytes     = 0x01C20000u,
        .ref_phys      = 0x15D43000u,
        .ref_bytes     = 0x01C20000u,
        .elem_bytes    = std::uint16_t(4u),
        ._pad          = std::uint16_t(0u),
        .src_ref_phys  = 0x00000000u,
        .src_ref_bytes = 0x00000000u,
        .src_dst_phys  = 0x00000000u,
        .name          = "im2row_QLinearConv6",
    },
    /* im2row */
    {
        .step_idx      = 19u,
        .out_phys      = 0x0C7E9000u,
        .out_bytes     = 0x01C20000u,
        .ref_phys      = 0x17963000u,
        .ref_bytes     = 0x01C20000u,
        .elem_bytes    = std::uint16_t(4u),
        ._pad          = std::uint16_t(0u),
        .src_ref_phys  = 0x00000000u,
        .src_ref_bytes = 0x00000000u,
        .src_dst_phys  = 0x00000000u,
        .name          = "im2row_QLinearConv8",
    },
    /* im2row */
    {
        .step_idx      = 22u,
        .out_phys      = 0x0F480000u,
        .out_bytes     = 0x00320000u,
        .ref_phys      = 0x19583000u,
        .ref_bytes     = 0x00320000u,
        .elem_bytes    = std::uint16_t(4u),
        ._pad          = std::uint16_t(0u),
        .src_ref_phys  = 0x00000000u,
        .src_ref_bytes = 0x00000000u,
        .src_dst_phys  = 0x00000000u,
        .name          = "im2row_QLinearMul9",
    },
    /* im2row */
    {
        .step_idx      = 25u,
        .out_phys      = 0x03EEC000u,
        .out_bytes     = 0x01C20000u,
        .ref_phys      = 0x198A3000u,
        .ref_bytes     = 0x01C20000u,
        .elem_bytes    = std::uint16_t(4u),
        ._pad          = std::uint16_t(0u),
        .src_ref_phys  = 0x00000000u,
        .src_ref_bytes = 0x00000000u,
        .src_dst_phys  = 0x00000000u,
        .name          = "im2row_QLinearConv10",
    }
};

