/* Auto-generated by gen_nn_baremetal.py - DO NOT EDIT */
#pragma once
#include "vta_nn_debug.h"

#define NN_NUM_DEBUG 9

static const vta::DebugLayerDesc nn_debug[NN_NUM_DEBUG] = {
    /* layer 0  suffix="QLinearConv1" */
    {
        .layer_idx     = 0u,
        .in_ref_phys   = 0x10113000u,
        .in_ref_bytes  = 0x02A30000u,
        .in_dst_phys   = 0x00001000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearConv1",
    },
    /* layer 1  suffix="QLinearConv2" */
    {
        .layer_idx     = 1u,
        .in_ref_phys   = 0x12B43000u,
        .in_ref_bytes  = 0x00960000u,
        .in_dst_phys   = 0x06211000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearConv2",
    },
    /* layer 2  suffix="QLinearConv3" */
    {
        .layer_idx     = 2u,
        .in_ref_phys   = 0x134A3000u,
        .in_ref_bytes  = 0x00960000u,
        .in_dst_phys   = 0x071D8000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearConv3",
    },
    /* layer 3  suffix="QLinearConv4" */
    {
        .layer_idx     = 3u,
        .in_ref_phys   = 0x13E03000u,
        .in_ref_bytes  = 0x01C20000u,
        .in_dst_phys   = 0x0819F000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearConv4",
    },
    /* layer 4  suffix="QLinearMul5" */
    {
        .layer_idx     = 4u,
        .in_ref_phys   = 0x15A23000u,
        .in_ref_bytes  = 0x00320000u,
        .in_dst_phys   = 0x0EB0E000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearMul5",
    },
    /* layer 5  suffix="QLinearConv6" */
    {
        .layer_idx     = 5u,
        .in_ref_phys   = 0x15D43000u,
        .in_ref_bytes  = 0x01C20000u,
        .in_dst_phys   = 0x0A4C4000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearConv6",
    },
    /* layer 6  suffix="QLinearConv8" */
    {
        .layer_idx     = 6u,
        .in_ref_phys   = 0x17963000u,
        .in_ref_bytes  = 0x01C20000u,
        .in_dst_phys   = 0x0C7E9000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearConv8",
    },
    /* layer 7  suffix="QLinearMul9" */
    {
        .layer_idx     = 7u,
        .in_ref_phys   = 0x19583000u,
        .in_ref_bytes  = 0x00320000u,
        .in_dst_phys   = 0x0F480000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearMul9",
    },
    /* layer 8  suffix="QLinearConv10" */
    {
        .layer_idx     = 8u,
        .in_ref_phys   = 0x198A3000u,
        .in_ref_bytes  = 0x01C20000u,
        .in_dst_phys   = 0x03EEC000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearConv10",
    }
};

