/* Auto-generated by the VTA baremetal codegen - DO NOT EDIT */
#pragma once
#include "vta_nn_debug.h"

#define NN_NUM_DEBUG 9

static const vta::DebugLayerDesc nn_debug[NN_NUM_DEBUG] = {
    /* layer 0  suffix="QLinearConv1" */
    {
        .layer_idx     = 0u,
        .in_ref_phys   = 0x200D9000u,
        .in_ref_bytes  = 0x02A30000u,
        .in_dst_phys   = 0x10001000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearConv1",
    },
    /* layer 1  suffix="QLinearConv2" */
    {
        .layer_idx     = 1u,
        .in_ref_phys   = 0x22B09000u,
        .in_ref_bytes  = 0x00960000u,
        .in_dst_phys   = 0x161ED000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearConv2",
    },
    /* layer 2  suffix="QLinearConv3" */
    {
        .layer_idx     = 2u,
        .in_ref_phys   = 0x23469000u,
        .in_ref_bytes  = 0x00960000u,
        .in_dst_phys   = 0x171B2000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearConv3",
    },
    /* layer 3  suffix="QLinearConv4" */
    {
        .layer_idx     = 3u,
        .in_ref_phys   = 0x23DC9000u,
        .in_ref_bytes  = 0x01C20000u,
        .in_dst_phys   = 0x18177000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearConv4",
    },
    /* layer 4  suffix="QLinearMul5" */
    {
        .layer_idx     = 4u,
        .in_ref_phys   = 0x259E9000u,
        .in_ref_bytes  = 0x00320000u,
        .in_dst_phys   = 0x1EAD4000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearMul5",
    },
    /* layer 5  suffix="QLinearConv6" */
    {
        .layer_idx     = 5u,
        .in_ref_phys   = 0x25D09000u,
        .in_ref_bytes  = 0x01C20000u,
        .in_dst_phys   = 0x1A496000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearConv6",
    },
    /* layer 6  suffix="QLinearConv8" */
    {
        .layer_idx     = 6u,
        .in_ref_phys   = 0x27929000u,
        .in_ref_bytes  = 0x01C20000u,
        .in_dst_phys   = 0x1C7B5000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearConv8",
    },
    /* layer 7  suffix="QLinearMul9" */
    {
        .layer_idx     = 7u,
        .in_ref_phys   = 0x29549000u,
        .in_ref_bytes  = 0x00320000u,
        .in_dst_phys   = 0x1F446000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearMul9",
    },
    /* layer 8  suffix="QLinearConv10" */
    {
        .layer_idx     = 8u,
        .in_ref_phys   = 0x29869000u,
        .in_ref_bytes  = 0x01C20000u,
        .in_dst_phys   = 0x13ECE000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearConv10",
    }
};

