package fpga.host.exporters

import fpga.host.models._
import fpga.host.transform._
import fpga.host.utils._
import vta.parsers.MetadataParser.insnCountFromFile

/** Rendering for `vta_hw_config.h` (the `ConfigParams` C type/define header).
  * Kept beside the other header renderers; the `Emittable` wiring is in
  * [[HeaderEmitters]].
  */
private[exporters] object HwConfigRender {
  def hwConfig(t: HwConfig.ConfigParams): String = {
    val inpT = HwConfig.ctypeFromLogWidth(t.logInpWidth)
    val outT = HwConfig.ctypeFromLogWidth(t.logOutWidth)
    val accT = HwConfig.ctypeFromLogWidth(t.logAccWidth)
    val wgtT = HwConfig.ctypeFromLogWidth(t.logWgtWidth)
    val logBlock = 31 - Integer.numberOfLeadingZeros(t.blockSize)

    val targetLines = t.target match {
      case Some(target) =>
        val targetUp = target.toUpperCase
        Seq(
          s"#if defined(XPAR_VTA_${targetUp}_0_BASEADDR)",
          s"#define VTA_VCR_BASE_ADDR XPAR_VTA_${targetUp}_0_BASEADDR",
          "#elif defined(XPAR_VTA_0_BASEADDR)"
        )
      case None =>
        Seq("#if defined(XPAR_VTA_0_BASEADDR)")
    }

    val lines = Seq(
      "#pragma once",
      "// Generated by gen_nn_baremetal.py - Do not edit manually.",
      s"// LOG_INP_WIDTH=${t.logInpWidth}, LOG_OUT_WIDTH=${t.logOutWidth}," +
        s" LOG_WGT_WIDTH=${t.logWgtWidth}, LOG_ACC_WIDTH=${t.logAccWidth}," +
        s" LOG_BLOCK=$logBlock",
      "#include <cstdint>",
      "#include <limits>",
      "extern \"C\" {",
      "#include \"xparameters.h\"",
      "}"
    ) ++ targetLines ++ Seq(
      "#define VTA_VCR_BASE_ADDR XPAR_VTA_0_BASEADDR",
      "#else",
      "#error \"VTA control base address not found in xparameters.h" +
        " (expected XPAR_VTA_<TARGET>_0_BASEADDR or XPAR_VTA_0_BASEADDR)\"",
      "#endif",
      "static constexpr std::uintptr_t VTA_VCR_BASE = VTA_VCR_BASE_ADDR;",
      s"using vta_inp_t = $inpT;",
      s"using vta_out_t = $outT;",
      s"using vta_acc_t = $accT;",
      s"using vta_wgt_t = $wgtT;",
      s"constexpr int VTA_BLOCK_SIZE = ${t.blockSize};",
      "constexpr std::int64_t VTA_OUT_MIN = std::numeric_limits<vta_out_t>::min();",
      "constexpr std::int64_t VTA_OUT_MAX = std::numeric_limits<vta_out_t>::max();"
    )

    lines.mkString("\n") + "\n"
  }
}

/** Rendering for the `nn_ddr_map.h` and `nn_exec_plan.h` C headers. Translated
  * from host/nnbaremetal/emit_headers.py. The `Emittable` wiring lives in
  * [[HeaderEmitters]]; this object holds the pure value->String rendering.
  */
private[exporters] object HeaderRender {

  private def getLayerMemRegionString(
    ddrBase: Long,
    id: Int,
    layer: Model.LayerInfo
  ): String = {

    val m = layer.mem
    val insnCount =
      insnCountFromFile(layer.binFiles("INSN"), m("INSN").byteSize)
    s"""    /* layer $id  suffix="${layer.suffix}" */
       |    {
       |        .ddr_base    = ${Model.hex32(ddrBase)},
       |        .insn_addr   = ${Model.hex32(ddrBase + m("INSN").offset)},
       |        .insn_count  = ${insnCount}u,
       |        .uop_phys    = ${Model.hex32(ddrBase + m("UOP").offset)},
       |        .uop_bytes   = ${Model.hex32(m("UOP").byteSize)},
       |        .inp_phys    = ${Model.hex32(ddrBase + m("INP").offset)},
       |        .inp_bytes   = ${Model.hex32(m("INP").byteSize)},
       |        .wgt_phys    = ${Model.hex32(ddrBase + m("WGT").offset)},
       |        .wgt_bytes   = ${Model.hex32(m("WGT").byteSize)},
       |        .acc_phys    = ${Model.hex32(ddrBase + m("ACC").offset)},
       |        .acc_bytes   = ${Model.hex32(m("ACC").byteSize)},
       |        .out_phys    = ${Model.hex32(ddrBase + m("OUT").offset)},
       |        .out_bytes   = ${Model.hex32(m("OUT").byteSize)},
       |    }""".stripMargin
  }

  /** Render `nn_ddr_map.h`. */
  def ddrMap(t: DdrMap): String = {
    val header = Seq(
      "/* Auto-generated by host/gen_nn_baremetal.py - DO NOT EDIT */",
      "#pragma once",
      "#include \"vta_nn.h\"",
      "",
      s"#define DDR_NN_BASE   ${Model.hex32(t.ddrBase)}",
      s"#define NN_NUM_LAYERS ${t.layers.length}",
      "",
      "static const vta::LayerDesc nn_layers[NN_NUM_LAYERS] = {"
    )
    val layerEntries = t.layers.zipWithIndex.map { case (layer, i) =>
      getLayerMemRegionString(t.ddrBase, i, layer)
    }
    header.mkString("\n") + "\n" + layerEntries.mkString(",\n") + "\n};\n\n"
  }

  /** Render `nn_exec_plan.h`. Translated from host/nnbaremetal/emit_headers.py
    * gen_exec_plan_header.
    */
  def execPlan(t: ExecPlan): String = {
    val plan = ExecPlanResolver.resolve(t)

    val header =
      s"""/* Auto-generated by host/gen_nn_baremetal.py - DO NOT EDIT */
         |#pragma once
         |#include \"vta_nn.h\"
         |
         |/* Final network output location */
         |#define NN_OUTPUT_ADDR  ${Model.hex32(plan.outputAddr)}
         |#define NN_OUTPUT_BYTES ${plan.outputBytes}u
         |
         |#define NN_NUM_STEPS ${plan.numSteps}u
         |
         |static const struct NnExecStep nn_exec_steps[NN_NUM_STEPS] = {""".stripMargin

    // Each rendered step begins with a newline and carries no trailing comma;
    // joining with "," reproduces the original comma-terminated layout (the
    // final entry is then naturally comma-free before the closing brace).
    header + plan.steps
      .map(renderStep(_, t.blockSize))
      .mkString(",") + "\n};\n\n"
  }

  // Format a pad tuple as a C initializer.
  private def fmtPad(p: (Int, Int, Int, Int)): String =
    s"{ ${p._1}, ${p._2}, ${p._3}, ${p._4} }"

  /** Render one resolved [[PlanStep]] to its `nn_exec_steps[]` entry, without a
    * trailing comma. Pure: every value is already resolved by
    * [[fpga.host.transform.ExecPlanResolver]].
    */
  private def renderStep(step: PlanStep, blockSize: Int): String = step match {
    case s: ReshapeStep           => renderReshape(s, blockSize)
    case s: Int32ChainStep        => renderInt32Chain(s)
    case s: VtaStep               => renderVta(s)
    case s: RescaleStep           => renderRescale(s)
    case s: QaddStep              => renderQadd(s)
    case s: ConcatStep            => renderConcat(s, blockSize)
    case s: DequantStep           => renderDequant(s)
    case s: QuantStep             => renderQuant(s)
    case s: ConvTransposeStep     => renderConvTranspose(s, blockSize)
    case s: ConvTransposeStubStep => renderConvTransposeStub(s)
    case s: UnsupportedStep       => renderUnsupported(s)
  }

  private def renderReshape(s: ReshapeStep, blockSize: Int): String = {
    val (comment, tag, member, namePrefix) = s.kind match {
      case ReshapeKind.FormatInput =>
        ("format_input for", "NN_STEP_FORMAT_INPUT", ".format_input", "format_")
      case ReshapeKind.Im2Row =>
        ("im2row for", "NN_STEP_IM2ROW", ".im2row", "im2row_")
    }
    s"""
       |    /* $comment ${s.layer} */
       |    { $tag, "$namePrefix${s.layer}", { $member = {
       |        ${Model.hex32(s.srcAddr)}, ${Model.hex32(s.inpAddr)},
       |        ${s.tensorCh}u, ${s.tensorH}u, ${s.tensorW}u,
       |        ${s.kh}u, ${s.kw}u, ${s.sh}u, ${s.sw}u,
       |        ${fmtPad(s.pad)},
       |        ${s.offsetA},
       |        ${s.outH}u, ${s.outW}u, ${blockSize}u
       |    } } }""".stripMargin
  }

  private def renderInt32Chain(s: Int32ChainStep): String =
    s"""
       |    /* int32 chain for ${s.layer} */
       |    { NN_STEP_INT32_CHAIN, "int32_chain_${s.layer}", { .int32_chain = {
       |        ${Model.hex32(s.srcAddr)}, ${Model.hex32(s.dstAddr)},
       |        ${s.nElems}u, ${s.offsetA},
       |        ${fmtPad(s.pad)},
       |        ${s.tensorCh}u, ${s.tensorH}u, ${s.tensorW}u
       |    } } }""".stripMargin

  private def renderVta(s: VtaStep): String =
    s"""
       |    /* step ${s.stepIdx} */
       |    { NN_STEP_VTA, "${s.layer}", { .vta = { ${s.vtaIdx} } } }""".stripMargin

  private def renderRescale(s: RescaleStep): String =
    s"""
       |    /* step ${s.stepIdx} rescale */
       |    { NN_STEP_RESCALE, "${s.layer}_rescale", { .rescale = { ${Model
        .hex32(s.outAddr)}, ${s.nElems}u, ${PyFmt.float(
        s.scale
      )}f, ${s.offsetC} } } }""".stripMargin

  private def renderQadd(s: QaddStep): String =
    s"""
       |    /* step ${s.stepIdx}: qadd */
       |    { NN_STEP_QADD, "${s.layer}", { .qadd = {
       |        ${Model.hex32(s.inpA)}, ${Model.hex32(s.inpB)}, ${Model.hex32(
        s.out
      )}, ${s.n}u,
       |        ${PyFmt.float(s.scaleA)}f, ${PyFmt.float(s.scaleB)}f, ${PyFmt
        .float(s.scaleC)}f,
       |        ${s.offsetA}, ${s.offsetB}, ${s.offsetC}
       |    } } }""".stripMargin

  private def renderConcat(s: ConcatStep, blockSize: Int): String =
    s"""
       |    /* step ${s.stepIdx}: concat */
       |    { NN_STEP_CONCAT, "${s.layer}", { .concat = {
       |        { ${s.inpAddrs.map(Model.hex32).mkString(", ")} },
       |        ${Model.hex32(s.out)}, ${s.nRows}u, ${s.nChPerInp}u, ${s.nbInp},
       |        { ${PyFmt.float(s.scaleA)}f, ${PyFmt.float(s.scaleB)}f, ${PyFmt
        .float(s.scaleU)}f, ${PyFmt.float(s.scaleV)}f },
       |        { ${s.offsetA}, ${s.offsetB}, ${s.offsetU}, ${s.offsetV} },
       |        ${PyFmt.float(s.scaleC)}f, ${s.offsetC}, ${blockSize}u
       |    } } }""".stripMargin

  private def renderDequant(s: DequantStep): String =
    s"""
       |    /* step ${s.stepIdx}: dequant */
       |    { NN_STEP_DEQUANT, "${s.layer}", { .dequant = {
       |        ${Model.hex32(s.inp)}, ${s.n}u, ${PyFmt.float(
        s.scaleA
      )}f, ${s.offsetA}
       |    } } }""".stripMargin

  private def renderQuant(s: QuantStep): String =
    s"""
       |    /* step ${s.stepIdx}: quant */
       |    { NN_STEP_QUANT, "${s.layer}", { .quant = {
       |        ${Model.hex32(s.out)}, ${s.n}u, ${PyFmt.float(
        s.scaleA
      )}f, ${s.offsetA}
       |    } } }""".stripMargin

  private def renderConvTranspose(
    s: ConvTransposeStep,
    blockSize: Int
  ): String =
    s"""
       |    /* step ${s.stepIdx}: convtranspose */
       |    { NN_STEP_CONVTRANSPOSE, "${s.layer}", { .convtranspose = {
       |        ${Model.hex32(s.wgtAddr)}, ${Model.hex32(s.biasAddr)}, ${if (
        s.hasBias
      ) 1
      else 0}u,
       |        ${s.tensorCh}u, ${s.tensorH}u, ${s.tensorW}u,
       |        ${s.outCh}u, ${s.outH}u, ${s.outW}u,
       |        ${s.kh}u, ${s.kw}u, ${s.sh}u,
       |        ${fmtPad(s.pad)},
       |        ${blockSize}u, ${s.nOut}u
       |    } } }""".stripMargin

  private def renderConvTransposeStub(s: ConvTransposeStubStep): String =
    s"""
       |    /* step ${s.stepIdx}: convtranspose ${s.layer} - no params */
       |    { NN_STEP_VTA, "${s.layer}", { .vta = { -1 } } }""".stripMargin

  private def renderUnsupported(s: UnsupportedStep): String =
    s"""
       |    /* step ${s.stepIdx}: ${s.processor} ${s.layer} - unsupported, skipped */
       |    { NN_STEP_VTA, "${s.layer}", { .vta = { -1 } } }""".stripMargin
}

/** `Emittable` instances for the header artifacts. */
trait HeaderEmitters {
  implicit val hwConfigIsEmittable: Emittable[HwConfig.ConfigParams] =
    Emittable(HwConfigRender.hwConfig)
  implicit val ddrMapIsEmittable: Emittable[DdrMap] =
    Emittable(HeaderRender.ddrMap)
  implicit val execPlanIsEmittable: Emittable[ExecPlan] =
    Emittable(HeaderRender.execPlan)
}
