package fpga.host.exporters

import fpga.host.models._
import fpga.host.transform.MemoryLayout

/** Rendering for the XSDB load TCL, the `.incbin` asm, and the linker fragment.
  * Translated from host/nnbaremetal/emit_load.py.
  */
private[exporters] object LoaderRender {

  /** Render an XSDB Tcl script that loads static model data (INSN/UOP/WGT/ACC),
    * optionally followed by input_nn.bin into the scratch DDR region.
    */
  def loadTcl(t: LoadTcl): String = {
    val lines =
      loadHeaderSection(t) ++
        layerSection(t.layers, t.ddrBase) ++
        extraBlobSection(t.extraBlobs) ++
        (if (t.includeInput) inputSection(t.compDir, t.layers, t.ddrBase)
         else Nil) ++
        Seq("# Resume ARM execution", "con")
    lines.mkString("\n") + "\n"
  }

  /** Banner + connect/stop preamble for `load_nn.tcl` / `load_nn_static.tcl`.
    */
  private def loadHeaderSection(t: LoadTcl): Seq[String] =
    Seq(
      "# Auto-generated by the VTA baremetal codegen - DO NOT EDIT",
      "#"
    ) ++ (if (t.includeInput)
            Seq(
              "# Loads static model data (INSN/UOP/WGT/ACC) and the network input",
              "# (input_nn.bin) into DDR via XSDB, then resumes the ARM application."
            )
          else
            Seq(
              "# Loads static model data (INSN/UOP/WGT/ACC) only.",
              "# input_nn.bin is NOT loaded - supplied at runtime (UART or other means)."
            )) ++ Seq(
      "#",
      "# Usage (from Vitis XSDB console or xsct shell):",
      s"#   source ${t.scriptName}",
      "",
      "connect",
      """targets -set -filter {name =~ "APU*"}""",
      "stop",
      "after 500",
      ""
    )

  /** One `dow` block per static VTA buffer (INSN/UOP/WGT/ACC) per layer. */
  private def layerSection(
    layers: Seq[Model.LayerInfo],
    ddrBase: Long
  ): Seq[String] =
    layers.zipWithIndex.flatMap { case (layer, i) =>
      val bufLines = Model.staticLoadOrder.flatMap { bufType =>
        val m = layer.mem(bufType)
        if (m.byteSize != 0 && !Model.isRuntimeAcc(layer, bufType)) {
          val binPath = os.Path(layer.binFiles(bufType), os.pwd).toString
          if (os.exists(os.Path(binPath))) {
            val addrStr = Model.hexAddr(ddrBase + m.offset)
            Seq(
              s"""puts "Loading ${layer.suffix} $bufType..."""",
              s"dow -data {$binPath} $addrStr"
            )
          } else Nil
        } else Nil
      }
      Seq(
        s"""# --- layer $i "${layer.suffix}" static model data ---"""
      ) ++ bufLines ++ Seq("")
    }

  /** CPU-op parameter blobs (convtranspose float weights/bias) - loaded at
    * their own absolute DDR addresses, same `dow` convention as the VTA
    * buffers.
    */
  private def extraBlobSection(extraBlobs: Seq[ExtraBlob]): Seq[String] =
    if (extraBlobs.nonEmpty) {
      Seq("# --- CPU-op parameter blobs (convtranspose weights/bias) ---") ++
        extraBlobs.flatMap { b =>
          if (b.size != 0 && os.exists(os.Path(b.path, os.pwd)))
            Seq(
              s"""puts "Loading ${b.label}..."""",
              s"dow -data {${b.path}} ${Model.hexAddr(b.addr)}"
            )
          else Nil
        } ++
        Seq("")
    } else Nil

  /** The "raw network input -> scratch" `dow` block shared by `load_nn.tcl`
    * (when `includeInput`) and `load_input.tcl`. Falls back to a WARNING +
    * `exit 1` when input_nn.bin is absent at codegen time. Ends with a trailing
    * blank line.
    */
  private def inputSection(
    compDir: String,
    layers: Seq[Model.LayerInfo],
    ddrBase: Long
  ): Seq[String] = {
    val inputNnPath = os.Path(compDir + "/input_nn.bin", os.pwd).toString
    val addrStr = Model.hexAddr(MemoryLayout.scratchAddr(layers, ddrBase))
    Seq(
      "# --- raw network input (scratch - ARM applies im2row at runtime) ---",
      s"""puts "Loading input_nn.bin (raw) -> $addrStr...""""
    ) ++ (if (os.exists(os.Path(inputNnPath))) {
            Seq(s"dow -data {$inputNnPath} $addrStr")
          } else {
            Seq(
              s"# WARNING: input_nn.bin not found at codegen time: $inputNnPath",
              s"""puts stderr "ERROR: input_nn.bin not found - place it at: $inputNnPath"""",
              "exit 1"
            )
          }) ++ Seq("")
  }

  /** Render `load_input.tcl` - loads only input_nn.bin into the scratch region.
    */
  def inputTcl(t: InputTcl): String = {
    val header =
      """# Auto-generated by the VTA baremetal codegen - DO NOT EDIT
        |#
        |# Loads input_nn.bin only - static model data is embedded in the ELF.
        |#
        |# Usage (from Vitis XSDB console or xsct shell):
        |#   source load_input.tcl
        |
        |connect
        |targets -set -filter {name =~ "APU*"}
        |stop
        |after 500
        |
        |""".stripMargin
    header ++ (
      inputSection(t.compDir, t.layers, t.ddrBase) ++ Seq(
        "# Resume ARM execution",
        "con"
      )
    ).mkString("\n") + "\n"
  }

  private def emitSection(secName: String, absPath: String): Seq[String] = {
    val binPath = os.Path(absPath, os.pwd).toString
    Seq(
      s"""    .section $secName, "a", %progbits""",
      s"    .align ${Model.incbinAlignLog2}"
    ) ++ (if (os.exists(os.Path(absPath, os.pwd))) {
            Seq(s"""    .incbin "$binPath"""")
          } else {
            println(s"WARNING: $absPath not found - section will be empty")
            Seq(
              s"    /* WARNING: binary not found at codegen time: $binPath */"
            )
          }) ++ Seq("")
  }

  /** Render `nn_bin_data.S` - one `.incbin` section per static buffer per
    * layer.
    */
  def asmIncbin(t: AsmIncbin): String = {
    val headerLines =
      s"""/* Auto-generated by the VTA baremetal codegen - DO NOT EDIT */
         |/*
         | * VTA static model data: one .incbin section per buffer per layer.
         | * Each section is placed at its DRAM address by nn_vta_sections.ld.
         | * Add this file as a source in your project and INCLUDE nn_vta_sections.ld
         | * inside your platform SECTIONS { ... } block.
         | */
         |
         |""".stripMargin

    val staticSections = Model
      .iterStaticBuffers(t.layers)
      .flatMap { case (i, layer, bufType, _) =>
        emitSection(
          Model.sectionName(i, bufType),
          os.Path(layer.binFiles(bufType), os.pwd).toString
        )
      }
      .toSeq

    // CPU-op parameter blobs (convtranspose float weights/bias).
    val extraBlobSections = t.extraBlobs.flatMap { b =>
      emitSection(b.label, b.path)
    }

    // Isolation-check golden inputs/outputs (--emit-layer-check only).
    val checkSections: Seq[String] = if (t.emitCheck) {
      t.layers.zipWithIndex.flatMap { case (layer, i) =>
        Model
          .refEntries(layer, i)
          .filter(e => e.size > 0 && e.file.nonEmpty)
          .flatMap(e =>
            emitSection(e.section, os.Path(e.file, os.pwd).toString)
          )
      }
    } else Nil

    headerLines ++ (staticSections ++ extraBlobSections ++ checkSections)
      .mkString("\n") + "\n"
  }

  /** Render `nn_vta_sections.ld` - placement of each `.incbin` section. */
  def linkerFragment(t: LinkerFragment): String = {
    val ddrBase = t.ddrBase
    val headerLines =
      """/* Auto-generated by the VTA baremetal codegen - DO NOT EDIT        */
        |/* VTA static model data linker fragment                             */
        |/*                                                                   */
        |/* Include this file inside the platform linker script generated.                    */
        |/* Example (in your lscript.ld):           */
        |/*   INCLUDE ../gen/nn_vta_sections.ld                                */
        |
        |""".stripMargin

    val staticLines = Model
      .iterStaticBuffers(t.layers)
      .map { case (i, _, bufType, m) =>
        val addr = ddrBase + m.offset
        val secName = Model.sectionName(i, bufType)
        s"$secName ${Model.hexAddr(addr)} : { KEEP(*($secName)) }"
      }
      .toSeq

    // CPU-op parameter blobs (convtranspose float weights/bias).
    val extraBlobLines = t.extraBlobs.map { b =>
      s"${b.label} ${Model.hexAddr(b.addr)} : { KEEP(*(${b.label})) }"
    }

    // Isolation-check golden inputs/outputs (--emit-layer-check only).
    val checkLines: Seq[String] = if (t.emitCheck) {
      t.layers.zipWithIndex.flatMap { case (layer, i) =>
        Model
          .refEntries(layer, i)
          .filter(e => e.size > 0 && e.file.nonEmpty)
          .map(e =>
            s"${e.section} ${Model.hexAddr(e.addr)} : { KEEP(*(${e.section})) }"
          )
      }
    } else Nil

    headerLines ++ (Seq(
      "SECTIONS {"
    ) ++ staticLines ++ extraBlobLines ++ checkLines ++ Seq("}"))
      .mkString("\n") + "\n"
  }
}

/** `Emittable` instances for the loader artifacts. */
trait LoaderEmitters {
  implicit val loadTclIsEmittable: Emittable[LoadTcl] =
    Emittable(LoaderRender.loadTcl)
  implicit val inputTclIsEmittable: Emittable[InputTcl] =
    Emittable(LoaderRender.inputTcl)
  implicit val asmIncbinIsEmittable: Emittable[AsmIncbin] =
    Emittable(LoaderRender.asmIncbin)
  implicit val linkerFragmentIsEmittable: Emittable[LinkerFragment] =
    Emittable(LoaderRender.linkerFragment)
}
