/**
 * run_nn.cc - Multi-layer VTA inference (XSCT method).
 *
 * DDR memory is pre-initialized via the XSCT script generated by the baremetal
 * codegen (load_nn_static.tcl): static model data (INSN/UOP/WGT/ACC) is loaded
 * before this binary starts; input_nn.bin is loaded separately via
 * load_input.tcl.
 *
 * To regenerate headers from a compiler output directory (from software/):
 *   make gen CONFIG=../../../config/vta_config.json DDR_BASE=0x10000000
 */

#include "nn_ddr_map.h"
#include "nn_exec_plan.h"
#include "vta_board.h"
#include "vta_hw_config.h"
#include "vta_nn.h"
#include <cstdlib>
extern "C" {
#include "xil_printf.h"
}
#ifdef NN_SD_LOADER
#include "nn_sd_manifest.h"
#include "vta_sd.h"
#ifndef NN_SD_DIR // without a subfolder -> card root
#define NN_SD_DIR ""
#endif
#endif

int main() {
  vta::board_init();
  xil_printf("=== VTA NN runner: %u step(s) ===\r\n",
             static_cast<unsigned>(NN_NUM_STEPS));

#ifdef NN_SD_LOADER
  // Load static model data (and the raw input) from the SD card into DDR,
  // replacing the XSDB/.incbin pre-load. See driver/src/vta_sd.cc.
  if (vta::sd_load_files("0:/" NN_SD_DIR, nn_sd_static_files,
                         NN_SD_NUM_STATIC) != 0) {
    xil_printf("ERROR: SD static-model load failed\r\n");
    return -1;
  }
#if NN_SD_HAS_INPUT
  if (vta::sd_load_files("0:/" NN_SD_DIR, &nn_sd_input_file, 1) != 0) {
    xil_printf("ERROR: SD input load failed\r\n");
    return -1;
  }
#endif
#endif

  std::uint32_t float_bytes = 0;
  bool ok = false;
  float *float_buf = vta::run_nn(VTA_VCR_BASE, nn_exec_steps, NN_NUM_STEPS,
                                 nn_layers, NN_NUM_LAYERS, &float_bytes, &ok);
  std::free(float_buf);

  if (!ok)
    return -1;
  xil_printf("=== NN done ===\r\n");
  return 0;
}
