/**
 * run_nn.cc - Multi-layer VTA inference, UART interactive loop.
 *
 * Static model data (INSN/UOP/WGT/ACC) must be pre-loaded into DDR via the
 * XSCT script generated by gen_nn_baremetal.py (load_nn.tcl) or embedded in
 * the ELF.  The raw network input is received over UART each iteration.
 *
 * Protocol
 * --------
 *   Board sends: "=== VTA NN runner: <N> step(s) ===\r\n"   (once, at boot)
 *   Loop:
 *     Board waits: trigger byte (0x01) from host
 *     Board sends: "input=<N> out=<M>\r\n"
 *     Board sends: "READY\r\n"
 *     Host sends:  <input_n_bytes> raw bytes (HWC INT8, no framing)
 *     Board runs inference (prints per-step logs)
 *     Board sends: "OUTPUT\r\n"
 *     Board sends: <out_n_bytes> raw bytes (INT8 from VTA OUT buffer,
 *                  or float bytes if the last step is DEQUANT with no QUANT)
 */

#include "nn_ddr_map.h"
#include "nn_exec_plan.h"
#include "vta_board.h"
#include "vta_hw_config.h"
#include "vta_nn.h"
#include <cstdint>
#include <cstdlib>
extern "C" {
#include "xil_cache.h"
#include "xil_printf.h"
}
#ifdef NN_SD_LOADER
#include "nn_sd_manifest.h"
#include "vta_sd.h"
#ifndef NN_SD_DIR // older manifest without a subfolder -> card root
#define NN_SD_DIR ""
#endif
#endif

// ---------------------------------------------------------------------------
// UART byte I/O
// ---------------------------------------------------------------------------

static void wait_for_trigger() {
  while (inbyte() != '\x01') {
  }
}

static void uart_recv(void *dst, std::uint32_t n) {
  auto *p = static_cast<std::uint8_t *>(dst);
  for (std::uint32_t i = 0; i < n; ++i)
    p[i] = inbyte();
}

static void uart_send(const void *src, std::uint32_t n) {
  const auto *p = static_cast<const std::uint8_t *>(src);
  for (std::uint32_t i = 0; i < n; ++i)
    outbyte(p[i]);
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

int main() {
  vta::board_init();
  xil_printf("=== VTA NN runner: %u step(s) ===\r\n",
             static_cast<unsigned>(NN_NUM_STEPS));

#ifdef NN_SD_LOADER
  // Load static model data from the SD card; the raw input still arrives over
  // UART each iteration (so NN_SD_HAS_INPUT is intentionally ignored here).
  if (vta::sd_load_files("0:/" NN_SD_DIR, nn_sd_static_files,
                         NN_SD_NUM_STATIC) != 0) {
    xil_printf("ERROR: SD static-model load failed\r\n");
    return -1;
  }
#endif

  std::uint32_t raw_addr = 0, input_n_bytes = 0;
  if (!vta::find_input(nn_exec_steps, NN_NUM_STEPS, &raw_addr,
                       &input_n_bytes)) {
    xil_printf("ERROR: no FORMAT_INPUT step - cannot use UART loop\r\n");
    return -1;
  }

  constexpr std::uint32_t out_addr = NN_OUTPUT_ADDR;
  constexpr std::uint32_t out_n_bytes = NN_OUTPUT_BYTES;

  while (true) {
    wait_for_trigger();
    xil_printf("input=%u out=%u\r\n", input_n_bytes, out_n_bytes);
    xil_printf("READY\r\n");

    // Receive raw HWC input into scratch DDR, flush cache for PL coherency.
    uart_recv(reinterpret_cast<void *>(raw_addr), input_n_bytes);
    Xil_DCacheFlushRange(raw_addr, input_n_bytes);

    // Run the full inference pipeline.
    std::uint32_t float_bytes = 0;
    bool ok = false;
    float *float_buf = vta::run_nn(VTA_VCR_BASE, nn_exec_steps, NN_NUM_STEPS,
                                   nn_layers, NN_NUM_LAYERS, &float_bytes, &ok);

    if (!ok) {
      xil_printf("=== inference failed, skipping output ===\r\n");
      continue;
    }

    // OUTPUT sentinel: host reads text lines until this marker, then switches
    // to raw binary receive to avoid mixing log output with payload bytes.
    xil_printf("OUTPUT\r\n");

    // Send output: float buffer if DEQUANT was the last step, INT8 OUT
    // otherwise.
    if (float_buf != nullptr) {
      uart_send(float_buf, float_bytes);
      std::free(float_buf);
    } else {
      uart_send(reinterpret_cast<const void *>(out_addr), out_n_bytes);
    }
  }
}
