# board_params.tcl - generated by build_fpga.py; do not edit by hand.
# board: zcu104

set board_name {zcu104}
set part {xczu7ev-ffvc1156-2-e}
set board_part {xilinx.com:zcu104:part0:1.1}
set is_versal {false}
set ps_ip {xilinx.com:ip:zynq_ultra_ps_e}
set ps_cell {zynq_ultra_ps_e_0}
set ps_preset_rule {xilinx.com:bd_rule:zynq_ultra_ps_e}
set ps_preset_config {apply_board_preset 1}
set board_repo {}
set pl_clock_mhz {100}
set pl_clock_property {PSU__CRL_APB__PL0_REF_CTRL__FREQMHZ}
set vta_cell {VTA_0}
set vta_vlnv {onera:user:VTA:0.2.0}
set ip_repo {/fixed/ip_repo}
set out_dir {/fixed/out}
set proj_dir {/fixed/out/project}
set jobs {4}

set ps_config {PSU__FPGA_PL0_ENABLE {1} PSU__USE__M_AXI_GP0 {1} PSU__USE__M_AXI_GP1 {0} PSU__USE__M_AXI_GP2 {0} PSU__USE__S_AXI_GP0 {1} PSU__USE__IRQ0 {1}}
set port_vta_dram_master {m_axi_gmem}
set port_vta_ctrl_slave {s_axi_control}
set port_vta_clk {ap_clk}
set port_vta_resetn {ap_rst_n}
set port_ps_dram_slave {S_AXI_HPC0_FPD}
set port_ps_ctrl_master {M_AXI_HPM0_FPD}
set port_ps_clk {pl_clk0}
set port_ps_resetn {pl_resetn0}
set ps_clk_aclks {maxihpm0_fpd_aclk saxihpc0_fpd_aclk}

set addresses {{zynq_ultra_ps_e_0/Data VTA_0/s_axi_control/reg0 0xA0000000 0x00010000} {VTA_0/m_axi_gmem VTA_0/s_axi_control/reg0 0xA0000000 0x00010000} {VTA_0/m_axi_gmem zynq_ultra_ps_e_0/SAXIGP0/HPC0_DDR_LOW 0x00000000 0x80000000} {VTA_0/m_axi_gmem zynq_ultra_ps_e_0/SAXIGP0/HPC0_LPS_OCM 0xFF000000 0x01000000} {VTA_0/m_axi_gmem zynq_ultra_ps_e_0/SAXIGP0/HPC0_QSPI 0xC0000000 0x20000000}}
set address_excludes {{zynq_ultra_ps_e_0/Data zynq_ultra_ps_e_0/SAXIGP0/HPC0_DDR_LOW} {zynq_ultra_ps_e_0/Data zynq_ultra_ps_e_0/SAXIGP0/HPC0_LPS_OCM} {zynq_ultra_ps_e_0/Data zynq_ultra_ps_e_0/SAXIGP0/HPC0_QSPI}}

