#!/usr/bin/env python3
"""
build_fpga.py - one-command FPGA synthesis for standalone VTA.

Drives the full chain, config- and board-parameterized, with no manual Vivado steps:

    config.json + board.json
      -> (mill)   emit Xilinx-shell RTL + package_ip.tcl   [stage 1]
      -> (vivado) package RTL as an IP-XACT IP in ip_repo/  [stage 2]
      -> (vivado) build block design -> synth -> impl
                  -> bitstream -> XSA                       [stage 3]
      -> vta_<board>.xsa  (+ .bit, reports, manifest.json)

The XSA produced here is exactly what `make -C ../software workspace XSA=...`
(create_vitis_workspace.py) consumes, so the two halves of the FPGA pipeline meet
at the XSA with no glue.

Board specifics live entirely in boards/<board>.json; the Vivado recipe
(build_fpga.tcl) is board-agnostic and parameterized by a generated
board_params.tcl. Retargeting a new board is a new JSON file, not a script edit.

Usage
-----
    # Source the Vivado environment first:
    source ~/Xilinx/2025.2/Vivado/settings64.sh

    python build_fpga.py --board zcu104 --config ../../../config/vta_config.json
    python build_fpga.py --board zcu104 --skip-emit       # reuse already-emitted RTL
    python build_fpga.py --board zcu104 --dry-run          # print the plan, run nothing

The VTA IP VLNV is read from the emitted package_ip.tcl, so it always matches the
RTL actually emitted (no hardcoded vendor:lib:name:version).
"""

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

# ---------------------------------------------------------------------------
# Repository layout (relative to this script)
# ---------------------------------------------------------------------------

SCRIPT_DIR = Path(__file__).resolve().parent          # src/fpga/synthesis/
REPO_ROOT = SCRIPT_DIR.parents[2]                      # standalone-vta/
TSIM_DIR = REPO_ROOT / "src" / "simulators" / "cycle_accurate_simulator"
BOARDS_DIR = SCRIPT_DIR / "boards"
BUILD_TCL = SCRIPT_DIR / "build_fpga.tcl"

DEFAULT_CONFIG = REPO_ROOT / "config" / "vta_config.json"
# Matches the Mill task default (DefaultXilinxConfig.defaultDir).
DEFAULT_EMIT_DIR = TSIM_DIR / "build" / "emitted" / "vta-xilinx-shell"
DEFAULT_OUT_DIR = SCRIPT_DIR / "build"


# ---------------------------------------------------------------------------
# Board definition
# ---------------------------------------------------------------------------


def load_board(board: str) -> dict:
    path = BOARDS_DIR / f"{board}.json"
    if not path.exists():
        avail = ", ".join(sorted(p.stem for p in BOARDS_DIR.glob("*.json"))) or "(none)"
        sys.exit(f"ERROR: board '{board}' not found at {path}\n       available: {avail}")
    with path.open() as f:
        return json.load(f)


def vlnv_from_emit(emit_dir: Path) -> str:
    """Read vendor:lib:name:version from the emitted package_ip.tcl."""
    pkg = emit_dir / "package_ip.tcl"
    if not pkg.exists():
        sys.exit(
            f"ERROR: emitted package_ip.tcl not found at {pkg}\n"
            f"       Run without --skip-emit, or run the Mill emit first."
        )
    text = pkg.read_text()
    fields = {}
    for key in ("ip_vendor", "ip_lib", "ip_name", "ip_version"):
        m = re.search(rf'set\s+{key}\s+"([^"]+)"', text)
        if not m:
            sys.exit(f"ERROR: could not parse '{key}' from {pkg}")
        fields[key] = m.group(1)
    return ":".join(fields[k] for k in ("ip_vendor", "ip_lib", "ip_name", "ip_version"))


# ---------------------------------------------------------------------------
# board_params.tcl generation
# ---------------------------------------------------------------------------


def _tcl_brace(value: str) -> str:
    """Wrap a scalar in braces so spaces/colons survive Tcl word-splitting."""
    return "{" + str(value) + "}"


def _subst(s: str, ps_cell: str, vta_cell: str) -> str:
    return s.replace("{ps_cell}", ps_cell).replace("{vta_cell}", vta_cell)


def render_board_params(
    board: dict,
    vta_cell: str,
    vta_vlnv: str,
    ip_repo: Path,
    out_dir: Path,
    proj_dir: Path,
    jobs: int,
) -> str:
    ps_cell = board["ps_cell"]

    def sub(s: str) -> str:
        return _subst(s, ps_cell, vta_cell)

    lines = [
        "# board_params.tcl - generated by build_fpga.py; do not edit by hand.",
        f"# board: {board['name']}",
        "",
        f"set board_name {_tcl_brace(board['name'])}",
        f"set part {_tcl_brace(board['part'])}",
        f"set board_part {_tcl_brace(board.get('board_part', ''))}",
        f"set is_versal {_tcl_brace(str(board.get('is_versal', False)).lower())}",
        f"set ps_ip {_tcl_brace(board['ps_ip'])}",
        f"set ps_cell {_tcl_brace(ps_cell)}",
        f"set ps_preset_rule {_tcl_brace(board.get('ps_preset_rule', ''))}",
        f"set ps_preset_config {_tcl_brace(board.get('ps_preset_config', 'apply_board_preset 1'))}",
        f"set board_repo {_tcl_brace(os.path.expanduser(board.get('board_repo', '')))}",
        f"set pl_clock_mhz {_tcl_brace(board['pl_clock_mhz'])}",
        f"set pl_clock_property {_tcl_brace(board.get('pl_clock_property', ''))}",
        f"set vta_cell {_tcl_brace(vta_cell)}",
        f"set vta_vlnv {_tcl_brace(vta_vlnv)}",
        f"set ip_repo {_tcl_brace(ip_repo.as_posix())}",
        f"set out_dir {_tcl_brace(out_dir.as_posix())}",
        f"set proj_dir {_tcl_brace(proj_dir.as_posix())}",
        f"set jobs {_tcl_brace(jobs)}",
        "",
    ]

    # PS config deltas as a flat {K V K V ...} list.
    ps_cfg_flat = " ".join(f"{k} {_tcl_brace(v)}" for k, v in board.get("ps_config", {}).items())
    lines.append(f"set ps_config {{{ps_cfg_flat}}}")

    # NoC config deltas as a flat {K V K V ...} list.
    noc_cfg = board.get("noc_config", {
        "MC2_FLIPPED_PINOUT": "true",
        "MC_CHANNEL_INTERLEAVING": "true",
        "MC_CHAN_REGION1": "DDR_LOW1",
        "MC_LP4_OVERWRITE_IO_PROP": "true",
        "MC_LP4_PIN_EFFICIENT": "true",
        "MC_SYSTEM_CLOCK": "Differential",
    })
    noc_cfg_flat = " ".join(f"{k} {_tcl_brace(v)}" for k, v in noc_cfg.items())
    lines.append(f"set noc_config {{{noc_cfg_flat}}}")

    ports = board["ports"]
    port_map = {
        "port_vta_dram_master": ports["vta_dram_master"],
        "port_vta_ctrl_slave": ports["vta_ctrl_slave"],
        "port_vta_clk": ports["vta_clk"],
        "port_vta_resetn": ports["vta_resetn"],
        "port_ps_dram_slave": ports["ps_dram_slave"],
        "port_ps_ctrl_master": ports["ps_ctrl_master"],
        "port_ps_clk": ports["ps_clk"],
        "port_ps_resetn": ports["ps_resetn"],
        "versal_ch0": ports.get("versal_ch0", "ch0_lpddr4_trip1"),
        "versal_ch1": ports.get("versal_ch1", "ch1_lpddr4_trip1"),
        "versal_clk": ports.get("versal_clk", "lpddr4_clk1"),
    }
    for k, v in port_map.items():
        lines.append(f"set {k} {_tcl_brace(v)}")
    lines.append("set ps_clk_aclks {" + " ".join(ports["ps_clk_aclks"]) + "}")
    lines.append("")

    # Address map + excludes, with {ps_cell}/{vta_cell} substituted.
    addr_items = []
    for a in board["addresses"]:
        addr_items.append(
            "{" + f"{sub(a['space'])} {sub(a['seg'])} {a['offset']} {a['range']}" + "}"
        )
    lines.append("set addresses {" + " ".join(addr_items) + "}")

    excl_items = []
    for e in board.get("address_excludes", []):
        excl_items.append("{" + f"{sub(e['space'])} {sub(e['seg'])}" + "}")
    lines.append("set address_excludes {" + " ".join(excl_items) + "}")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Command running
# ---------------------------------------------------------------------------


def run(cmd: list[str], cwd: Path, dry_run: bool, stage: str) -> None:
    printable = " ".join(str(c) for c in cmd)
    print(f"\n[{stage}] (cwd={cwd})\n    {printable}")
    if dry_run:
        return
    env = os.environ.copy()
    libudev = Path("/lib/x86_64-linux-gnu/libudev.so.1")
    if libudev.exists() and "vivado" in str(cmd[0]).lower():
        env["LD_PRELOAD"] = str(libudev)
    result = subprocess.run([str(c) for c in cmd], cwd=str(cwd), env=env)
    if result.returncode != 0:
        log_hint = cwd / "vivado.log"
        extra = f"\n       see {log_hint}" if log_hint.exists() else ""
        sys.exit(f"ERROR: [{stage}] command failed (exit {result.returncode}).{extra}")


def _git_sha() -> str:
    try:
        out = subprocess.run(
            ["git", "-C", str(REPO_ROOT), "rev-parse", "HEAD"],
            capture_output=True, text=True,
        )
        return out.stdout.strip() if out.returncode == 0 else "(unknown)"
    except Exception:
        return "(unknown)"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _timing_met(report: Path):
    """Parse Vivado's timing summary verdict. Returns True/False, or None if unknown.

    write_bitstream succeeds even when timing fails, so the verdict must be read
    from the report rather than inferred from the run completing.
    """
    if not report.exists():
        return None
    text = report.read_text()
    if "Timing constraints are not met" in text:
        return False
    if "All user specified timing constraints are met" in text:
        return True
    return None


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build a VTA FPGA bitstream + XSA from a config and a board definition.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--board", default="zcu104", help="Board name (boards/<board>.json).")
    parser.add_argument("--config", default=str(DEFAULT_CONFIG),
                        metavar="PATH", help="VTA hardware config JSON (drives the RTL emit).")
    parser.add_argument("--out", default=str(DEFAULT_OUT_DIR),
                        metavar="DIR", help="Output directory for the XSA, bitstream, reports.")
    parser.add_argument("--emit-dir", default=str(DEFAULT_EMIT_DIR),
                        metavar="DIR", help="Where the Mill emit writes RTL + package_ip.tcl.")
    parser.add_argument("--jobs", type=int, default=min(4, os.cpu_count() or 4),
                        help="Parallel jobs for synthesis/implementation.")
    parser.add_argument("--skip-emit", action="store_true",
                        help="Reuse an existing emit (skip stage 1 Mill).")
    parser.add_argument("--skip-package", action="store_true",
                        help="Reuse an existing packaged IP (skip stage 2).")
    parser.add_argument("--vivado", default="vivado", help="Vivado executable.")
    parser.add_argument("--mill", default=str(TSIM_DIR / "mill"), help="Mill wrapper.")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print the plan and the generated board_params.tcl; run nothing.")
    args = parser.parse_args()

    board = load_board(args.board)
    config = Path(args.config).resolve()
    out_dir = Path(args.out).resolve()
    emit_dir = Path(args.emit_dir).resolve()
    ip_repo = emit_dir / "ip_repo"
    proj_dir = out_dir / "project"
    vta_cell = "VTA_0"  # block-design instance name (arbitrary; addresses reference it)

    if not config.exists() and not args.skip_emit:
        sys.exit(f"ERROR: config not found: {config}")

    # Tool availability (skipped in dry-run so it works without Xilinx tools).
    if not args.dry_run:
        if not args.skip_emit and not Path(args.mill).exists() and not shutil.which(args.mill):
            sys.exit(f"ERROR: mill not found: {args.mill}")
        if shutil.which(args.vivado) is None:
            sys.exit(
                f"ERROR: '{args.vivado}' not on PATH.\n"
                f"       source <Xilinx>/Vivado/settings64.sh first."
            )
        out_dir.mkdir(parents=True, exist_ok=True)

    print("=== VTA FPGA build ===")
    print(f"  board      : {board['name']}  (part {board['part']})")
    print(f"  config     : {config}")
    print(f"  emit dir   : {emit_dir}")
    print(f"  output dir : {out_dir}")
    print(f"  jobs       : {args.jobs}")

    # --- Stage 1: emit Xilinx-shell RTL for this config ---
    if not args.skip_emit:
        # Mill's config resolver (BinaryReader.parseConfigJson) always joins
        # vta.config.file to <repo>/config/, so it expects a name relative to that
        # directory, not an absolute path. Compute and validate that.
        config_dir = (REPO_ROOT / "config").resolve()
        mill_cfg = os.path.relpath(config, config_dir)
        if mill_cfg.startswith(".."):
            sys.exit(
                f"ERROR: --config must live under {config_dir} (Mill resolves it there).\n"
                f"       got: {config}"
            )
        run(
            [args.mill, f"-Dvta.config.file={mill_cfg}", "emitVtaFpgaConfig", str(emit_dir)],
            cwd=TSIM_DIR, dry_run=args.dry_run, stage="1/3 emit RTL",
        )
    else:
        print("\n[1/3 emit RTL] skipped (--skip-emit)")

    # --- Stage 2: package the emitted RTL as an IP-XACT IP ---
    if not args.skip_package:
        run(
            [args.vivado, "-mode", "batch", "-source", str(emit_dir / "package_ip.tcl"),
             "-tclargs", "--part", board["part"]],
            cwd=emit_dir, dry_run=args.dry_run, stage="2/3 package IP",
        )
    else:
        print("\n[2/3 package IP] skipped (--skip-package)")

    # --- VLNV is read from the emit so it always matches the RTL ---
    if args.dry_run and not (emit_dir / "package_ip.tcl").exists():
        vta_vlnv = "onera:user:VTA:0.2.0  (placeholder; emit dir not present in dry-run)"
    else:
        vta_vlnv = vlnv_from_emit(emit_dir)
    print(f"  VTA IP     : {vta_vlnv}")

    # --- Stage 3: build project -> bitstream -> XSA ---
    params_text = render_board_params(
        board, vta_cell, vta_vlnv.split()[0], ip_repo, out_dir, proj_dir, args.jobs
    )
    params_file = out_dir / "board_params.tcl"
    if args.dry_run:
        print("\n--- generated board_params.tcl ---")
        print(params_text)
        print("--- end board_params.tcl ---")
    else:
        params_file.write_text(params_text)
        print(f"\n[3/3 build] wrote {params_file}")

    run(
        [args.vivado, "-mode", "batch", "-source", str(BUILD_TCL), "-tclargs", str(params_file)],
        cwd=out_dir, dry_run=args.dry_run, stage="3/3 build",
    )

    # --- Timing verdict (parsed from the post-route report) ---
    timing_met = _timing_met(out_dir / "timing_summary.rpt") if not args.dry_run else None

    # --- Provenance manifest ---
    xsa = out_dir / f"vta_{board['name']}.xsa"
    manifest = {
        "board": board["name"],
        "part": board["part"],
        "config": str(config),
        "config_sha256": _sha256(config) if config.exists() else None,
        "vta_vlnv": vta_vlnv.split()[0],
        "git_sha": _git_sha(),
        "xsa": str(xsa),
        "timing_met": timing_met,
        "built_at": datetime.now().isoformat(timespec="seconds"),
    }
    if args.dry_run:
        print("\n--- manifest.json (preview) ---")
        print(json.dumps(manifest, indent=2))
        print("\n=== DRY RUN complete (nothing executed) ===")
        return

    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")

    is_versal = board.get("is_versal", False)
    ext = "pdi" if is_versal else "bit"
    bit = out_dir / f"vta_{board['name']}.{ext}"
    software_dir = REPO_ROOT / "src" / "fpga" / "software"
    timing_str = {True: "MET", False: "NOT MET", None: "unknown"}[timing_met]
    print("\n=== Done ===")
    print(f"  XSA      : {xsa}")
    print(f"  Image    : {bit}")
    print(f"  Reports  : {out_dir / 'timing_summary.rpt'}, {out_dir / 'utilization.rpt'}")
    print(f"  Manifest : {out_dir / 'manifest.json'}")
    print(f"  Timing   : {timing_str}")
    if timing_met is False:
        print(
            "\n  !! WARNING: timing constraints are NOT met. The bitstream was still\n"
            "     written (Vivado does this regardless of slack) but is NOT reliable on\n"
            f"     hardware at this clock. Lower pl_clock_mhz in boards/{board['name']}.json\n"
            "     or target a larger/faster part, then rebuild. See timing_summary.rpt."
        )
    print("\nNext: create the Vitis platform from the XSA:")
    print(f"  make -C {software_dir} workspace XSA={xsa} CPU={board['cpu']}")


if __name__ == "__main__":
    main()
