/* Auto-generated by the VTA baremetal codegen - DO NOT EDIT */
/*
 * SD-card manifest: file -> DDR address map for the runtime sd loader
 * (driver/src/vta_sd.cc). Copy the staged files in gen/sd_card/ to the
 * root of a FAT32 SD card, then run a DATA_LOADER=sd build.
 */
#ifndef NN_SD_MANIFEST_H
#define NN_SD_MANIFEST_H
#include "vta_sd.h"

/* SD subfolder the files live in (path prefix, trailing slash); empty
 * = card root. The app opens "0:/" NN_SD_DIR <filename>. */
#define NN_SD_DIR ""

static const vta::SdFile nn_sd_static_files[] = {
    {"instructionsQLinearConv1.bin", 0x10051000u, 944u},
    {"uopQLinearConv1.bin", 0x10050000u, 396u},
    {"weightQLinearConv1.bin", 0x10035000u, 512u},
    {"accumulatorQLinearConv1_block.bin", 0x10036000u, 50176u},
    {"instructionsMaxPool2.bin", 0x10013000u, 15776u},
    {"uopMaxPool2.bin", 0x10012000u, 2356u},
    {"instructionsQLinearConv3.bin", 0x1006A000u, 272u},
    {"uopQLinearConv3.bin", 0x10069000u, 284u},
    {"weightQLinearConv3.bin", 0x10064000u, 2560u},
    {"accumulatorQLinearConv3_block.bin", 0x10065000u, 7168u},
    {"instructionsMaxPool4.bin", 0x1001B000u, 2096u},
    {"uopMaxPool4.bin", 0x1001A000u, 304u},
    {"instructionsQLinearConv5.bin", 0x10084000u, 288u},
    {"uopQLinearConv5.bin", 0x10083000u, 804u},
    {"weightQLinearConv5.bin", 0x10072000u, 51200u},
    {"accumulatorQLinearConv5_block.bin", 0x1007F000u, 8192u},
    {"instructionsQLinearConv6.bin", 0x1008F000u, 256u},
    {"uopQLinearConv6.bin", 0x1008E000u, 196u},
    {"weightQLinearConv6.bin", 0x10087000u, 12288u},
    {"accumulatorQLinearConv6_block.bin", 0x1008A000u, 6144u},
    {"instructionsQLinearConv7.bin", 0x10096000u, 176u},
    {"uopQLinearConv7.bin", 0x10095000u, 28u},
    {"weightQLinearConv7.bin", 0x10092000u, 1536u},
    {"accumulatorQLinearConv7_block.bin", 0x10093000u, 1024u},
};
#define NN_SD_NUM_STATIC 24u

#define NN_SD_HAS_INPUT 0

#define NN_SD_HAS_REFS 0

#endif /* NN_SD_MANIFEST_H */
