#!/usr/bin/env bash
#*****************************************************************************************
# synth_netlist.sh - OOC-synthesize VTAShell to a gate-level netlist for post-synth sim.
#
# Generates ooc_params.tcl (from a boards/<board>.json part) and runs ../ooc_netlist.tcl,
# producing <out>/VTAShell_funcsim.v (mode=synth) or also <out>/VTAShell_timesim.v + .sdf
# (mode=impl). No hand-written params file.
#
#   synth_netlist.sh --board zcu104 --sv-dir <emitVtaSimConfig out> --out <dir> [--mode synth|impl] [--jobs N]
#
# Prereq: source <Xilinx>/2025.2/Vivado/settings64.sh
#*****************************************************************************************
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYNTH_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"   # src/fpga/synthesis (holds ooc_netlist.tcl, boards/)
REPO="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null || echo "$SCRIPT_DIR/../../../..")"

BOARD="zcu104"
SV_DIR="$REPO/src/simulators/cycle_accurate_simulator/build/emitted/vta-sim-shell"
OUT=""
MODE="synth"
JOBS=8
TOP="VTAShell"
CLK_PORT="clock"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --board)    BOARD="$2"; shift 2 ;;
    --sv-dir)   SV_DIR="$2"; shift 2 ;;
    --out)      OUT="$2"; shift 2 ;;
    --mode)     MODE="$2"; shift 2 ;;
    --jobs)     JOBS="$2"; shift 2 ;;
    --top)      TOP="$2"; shift 2 ;;
    --clk-port) CLK_PORT="$2"; shift 2 ;;
    -h|--help)  sed -n '2,14p' "$0"; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 1 ;;
  esac
done

[[ -n "$OUT" ]] || { echo "ERROR: pass --out <dir>" >&2; exit 1; }
command -v vivado >/dev/null || { echo "ERROR: vivado not on PATH - source Vivado settings64.sh" >&2; exit 1; }
BOARD_JSON="$SYNTH_DIR/boards/$BOARD.json"
[[ -f "$BOARD_JSON" ]] || { echo "ERROR: board file not found: $BOARD_JSON" >&2; exit 1; }
[[ -d "$SV_DIR" && -f "$SV_DIR/$TOP.sv" ]] || { echo "ERROR: $SV_DIR/$TOP.sv missing (emit it first)" >&2; exit 1; }

PART=$(python3 -c "import json,sys;print(json.load(open('$BOARD_JSON'))['part'])")
MHZ=$(python3 -c "import json;print(json.load(open('$BOARD_JSON')).get('pl_clock_mhz',100))")
PERIOD=$(python3 -c "print(1000.0/$MHZ)")

mkdir -p "$OUT"
PARAMS="$OUT/ooc_params.tcl"
cat > "$PARAMS" <<EOF
# auto-generated by synth_netlist.sh - do not edit
set part          $PART
set sv_dir        $SV_DIR
set top           $TOP
set out_dir       $OUT
set proj_dir      $OUT/proj
set clk_port      $CLK_PORT
set clk_period_ns $PERIOD
set mode          $MODE
set jobs          $JOBS
EOF

echo "[synth_netlist] board=$BOARD part=$PART top=$TOP mode=$MODE sv_dir=$SV_DIR out=$OUT"
vivado -mode batch -source "$SYNTH_DIR/ooc_netlist.tcl" -tclargs "$PARAMS" -log "$OUT/vivado.log" -journal "$OUT/vivado.jou"
echo "[synth_netlist] netlist -> $OUT/${TOP}_funcsim.v"
