/* Auto-generated by the VTA baremetal codegen - DO NOT EDIT */
#pragma once
#include "vta_cpu_ops_debug.h"

/*
 * Coverage: only CPU ops whose output buffer equals a VTA layer's
 * golden INP/ACC dump are checked (FORMAT_INPUT / IM2ROW / INT32_CHAIN).
 * Other CPU ops (rescale / qadd / concat / dequant / quant) are
 * absent from the table and silently skipped at runtime.
 *
 * Isolation-mode source fields (src_ref_*, src_dst_phys) preload each
 * op's INPUT with a known-good golden (raw image for format_input, the
 * producer layer's pre-rescale out_ref for im2row/int32_chain) so a bad
 * upstream layer does not cascade.  The runtime replays the producer
 * rescale before the reshape.  Entries left at 0 (no embedded golden,
 * e.g. --emit-layer-check not run) fall back to the preloaded buffer.
 *
 * Skipped at codegen:
 *   - format_QLinearConv1 (no upstream golden - isolation fallback)
 *   - int32_chain_MaxPool2 (no golden input embedded)
 *   - im2row_QLinearConv3 (no upstream golden - isolation fallback)
 *   - int32_chain_MaxPool4 (no golden input embedded)
 *   - im2row_QLinearConv5 (no upstream golden - isolation fallback)
 *   - im2row_QLinearConv6 (no upstream golden - isolation fallback)
 *   - im2row_QLinearConv7 (no upstream golden - isolation fallback)
 */

#define NN_NUM_CPU_DEBUG 5u

static const vta::DebugCpuStep nn_cpu_debug[NN_NUM_CPU_DEBUG] = {
    /* format_input */
    {
        .step_idx      = 0u,
        .out_phys      = 0x1001C000u,
        .out_bytes     = 0x00018800u,
        .ref_phys      = 0x10098000u,
        .ref_bytes     = 0x00018800u,
        .elem_bytes    = std::uint16_t(4u),
        ._pad          = std::uint16_t(0u),
        .src_ref_phys  = 0x00000000u,
        .src_ref_bytes = 0x00000000u,
        .src_dst_phys  = 0x00000000u,
        .name          = "format_QLinearConv1",
    },
    /* im2row */
    {
        .step_idx      = 6u,
        .out_phys      = 0x10052000u,
        .out_bytes     = 0x00011800u,
        .ref_phys      = 0x100B1000u,
        .ref_bytes     = 0x00011800u,
        .elem_bytes    = std::uint16_t(4u),
        ._pad          = std::uint16_t(0u),
        .src_ref_phys  = 0x00000000u,
        .src_ref_bytes = 0x00000000u,
        .src_dst_phys  = 0x00000000u,
        .name          = "im2row_QLinearConv3",
    },
    /* im2row */
    {
        .step_idx      = 12u,
        .out_phys      = 0x1006B000u,
        .out_bytes     = 0x00006400u,
        .ref_phys      = 0x100C3000u,
        .ref_bytes     = 0x00006400u,
        .elem_bytes    = std::uint16_t(4u),
        ._pad          = std::uint16_t(0u),
        .src_ref_phys  = 0x00000000u,
        .src_ref_bytes = 0x00000000u,
        .src_dst_phys  = 0x00000000u,
        .name          = "im2row_QLinearConv5",
    },
    /* im2row */
    {
        .step_idx      = 15u,
        .out_phys      = 0x10085000u,
        .out_bytes     = 0x00002000u,
        .ref_phys      = 0x100CA000u,
        .ref_bytes     = 0x00002000u,
        .elem_bytes    = std::uint16_t(4u),
        ._pad          = std::uint16_t(0u),
        .src_ref_phys  = 0x00000000u,
        .src_ref_bytes = 0x00000000u,
        .src_dst_phys  = 0x00000000u,
        .name          = "im2row_QLinearConv6",
    },
    /* im2row */
    {
        .step_idx      = 18u,
        .out_phys      = 0x10090000u,
        .out_bytes     = 0x00001800u,
        .ref_phys      = 0x100CC000u,
        .ref_bytes     = 0x00001800u,
        .elem_bytes    = std::uint16_t(4u),
        ._pad          = std::uint16_t(0u),
        .src_ref_phys  = 0x00000000u,
        .src_ref_bytes = 0x00000000u,
        .src_dst_phys  = 0x00000000u,
        .name          = "im2row_QLinearConv7",
    }
};

