/* Auto-generated by the VTA baremetal codegen - DO NOT EDIT */
#pragma once
#include "vta_nn_debug.h"

#define NN_NUM_DEBUG 7

static const vta::DebugLayerDesc nn_debug[NN_NUM_DEBUG] = {
    /* layer 0  suffix="QLinearConv1" */
    {
        .layer_idx     = 0u,
        .in_ref_phys   = 0x10098000u,
        .in_ref_bytes  = 0x00018800u,
        .in_dst_phys   = 0x1001C000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearConv1",
    },
    /* layer 1  suffix="MaxPool2" */
    {
        .layer_idx     = 1u,
        .in_ref_phys   = 0x100B1000u,
        .in_ref_bytes  = 0x00000000u,
        .in_dst_phys   = 0x10001000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "MaxPool2",
    },
    /* layer 2  suffix="QLinearConv3" */
    {
        .layer_idx     = 2u,
        .in_ref_phys   = 0x100B1000u,
        .in_ref_bytes  = 0x00011800u,
        .in_dst_phys   = 0x10052000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearConv3",
    },
    /* layer 3  suffix="MaxPool4" */
    {
        .layer_idx     = 3u,
        .in_ref_phys   = 0x100C3000u,
        .in_ref_bytes  = 0x00000000u,
        .in_dst_phys   = 0x10017000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "MaxPool4",
    },
    /* layer 4  suffix="QLinearConv5" */
    {
        .layer_idx     = 4u,
        .in_ref_phys   = 0x100C3000u,
        .in_ref_bytes  = 0x00006400u,
        .in_dst_phys   = 0x1006B000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearConv5",
    },
    /* layer 5  suffix="QLinearConv6" */
    {
        .layer_idx     = 5u,
        .in_ref_phys   = 0x100CA000u,
        .in_ref_bytes  = 0x00002000u,
        .in_dst_phys   = 0x10085000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearConv6",
    },
    /* layer 6  suffix="QLinearConv7" */
    {
        .layer_idx     = 6u,
        .in_ref_phys   = 0x100CC000u,
        .in_ref_bytes  = 0x00001800u,
        .in_dst_phys   = 0x10090000u,
        .out_ref_phys  = 0x00000000u,
        .out_ref_bytes = 0x00000000u,
        .name          = "QLinearConv7",
    }
};

