/* Auto-generated by the VTA baremetal codegen - DO NOT EDIT */
/*
 * SD-card manifest: file -> DDR address map for the runtime sd loader
 * (driver/src/vta_sd.cc). Copy the staged files in gen/sd_card/ to the
 * root of a FAT32 SD card, then run a DATA_LOADER=sd build.
 */
#ifndef NN_SD_MANIFEST_H
#define NN_SD_MANIFEST_H
#include "vta_sd.h"

/* SD subfolder the files live in (path prefix, trailing slash); empty
 * = card root. The app opens "0:/" NN_SD_DIR <filename>. */
#define NN_SD_DIR ""

static const vta::SdFile nn_sd_static_files[] = {
    {"instructionsQLinearConv1.bin", 0x00051000u, 944u},
    {"uopQLinearConv1.bin", 0x00050000u, 396u},
    {"weightQLinearConv1.bin", 0x00035000u, 2048u},
    {"accumulatorQLinearConv1_block.bin", 0x00036000u, 50176u},
    {"instructionsMaxPool2.bin", 0x00013000u, 15776u},
    {"uopMaxPool2.bin", 0x00012000u, 2356u},
    {"instructionsQLinearConv3.bin", 0x0006C000u, 272u},
    {"uopQLinearConv3.bin", 0x0006B000u, 284u},
    {"weightQLinearConv3.bin", 0x00064000u, 10240u},
    {"accumulatorQLinearConv3_block.bin", 0x00067000u, 7168u},
    {"instructionsMaxPool4.bin", 0x0001B000u, 2096u},
    {"uopMaxPool4.bin", 0x0001A000u, 304u},
    {"instructionsQLinearConv5.bin", 0x000AB000u, 288u},
    {"uopQLinearConv5.bin", 0x000AA000u, 804u},
    {"weightQLinearConv5.bin", 0x00074000u, 204800u},
    {"accumulatorQLinearConv5_block.bin", 0x000A6000u, 8192u},
    {"instructionsQLinearConv6.bin", 0x000BF000u, 256u},
    {"uopQLinearConv6.bin", 0x000BE000u, 196u},
    {"weightQLinearConv6.bin", 0x000AE000u, 49152u},
    {"accumulatorQLinearConv6_block.bin", 0x000BA000u, 6144u},
    {"instructionsQLinearConv7.bin", 0x000C7000u, 176u},
    {"uopQLinearConv7.bin", 0x000C6000u, 28u},
    {"weightQLinearConv7.bin", 0x000C2000u, 6144u},
    {"accumulatorQLinearConv7_block.bin", 0x000C4000u, 1024u},
};
#define NN_SD_NUM_STATIC 24u

#define NN_SD_HAS_INPUT 0

#define NN_SD_HAS_REFS 0

#endif /* NN_SD_MANIFEST_H */
