"""Emitters for XSDB load TCL, the .incbin asm, and the linker fragment."""

import os
from pathlib import Path
from typing import List, Optional

from .model import (
    DependencyInfo,
    INCBIN_ALIGN_LOG2,
    LayerInfo,
    STATIC_LOAD_ORDER,
    _is_runtime_acc,
    iter_static_buffers,
)
from .layout import scratch_addr


def gen_tcl(
    layers: List[LayerInfo],
    ddr_base: int,
    comp_dir: str,
    out_path: str,
    dep_info: Optional[DependencyInfo] = None,
    include_input: bool = True,
    extra_blobs: Optional[List] = None,
) -> None:
    """Generate an XSDB Tcl script that loads static model data (INSN/UOP/WGT/ACC).

    If include_input is True (default), input_nn.bin is also loaded into the
    scratch DDR region (for the run_nn flow where input is pre-loaded).
    If False, only static model data is loaded (for run_nn_uart / test_gemm).
    """
    L: List[str] = []
    L.append("# Auto-generated by host/gen_nn_baremetal.py - DO NOT EDIT")
    L.append("#")
    if include_input:
        L.append("# Loads static model data (INSN/UOP/WGT/ACC) and the network input")
        L.append(
            "# (input_nn.bin) into DDR via XSDB, then resumes the ARM application."
        )
    else:
        L.append("# Loads static model data (INSN/UOP/WGT/ACC) only.")
        L.append(
            "# input_nn.bin is NOT loaded - supplied at runtime (UART or other means)."
        )
    L.append("#")
    L.append("# Usage (from Vitis XSDB console or xsct shell):")
    script_name = os.path.basename(out_path)
    L.append(f"#   source {script_name}")
    L.append("")
    L.append("connect")
    L.append('targets -set -filter {name =~ "APU*"}')
    L.append("stop")
    L.append("after 500")
    L.append("")

    for i, layer in enumerate(layers):
        L.append(f'# --- layer {i} "{layer.suffix}" static model data ---')
        for buf_type in STATIC_LOAD_ORDER:
            m = layer.mem[buf_type]
            if m.size == 0:
                continue
            if _is_runtime_acc(layer, buf_type):
                continue  # int32/maxpool ACC is runtime input, not static
            bin_path = os.path.abspath(layer.bin_files[buf_type])
            if os.path.isfile(bin_path):
                addr_str = f"0x{ddr_base + m.offset:08X}"
                L.append(f'puts "Loading {layer.suffix} {buf_type}..."')
                L.append(f"dow -data {{{bin_path}}} {addr_str}")
        L.append("")

    # CPU-op parameter blobs (convtranspose float weights/bias) - loaded at their
    # own absolute DDR addresses, same dow convention as the VTA buffers above.
    if extra_blobs:
        L.append("# --- CPU-op parameter blobs (convtranspose weights/bias) ---")
        for label, path, addr, size in extra_blobs:
            if size and os.path.isfile(path):
                L.append(f'puts "Loading {label}..."')
                L.append(f"dow -data {{{path}}} 0x{addr:08X}")
        L.append("")

    if include_input:
        input_nn_path = os.path.abspath(os.path.join(comp_dir, "input_nn.bin"))
        raw_phys = scratch_addr(layers, ddr_base)
        addr_str = f"0x{raw_phys:08X}"
        L.append(
            "# --- raw network input (scratch - ARM applies im2row at runtime) ---"
        )
        L.append(f'puts "Loading input_nn.bin (raw) -> {addr_str}..."')
        if os.path.isfile(input_nn_path):
            L.append(f"dow -data {{{input_nn_path}}} {addr_str}")
        else:
            L.append(
                f"# WARNING: input_nn.bin not found at codegen time: {input_nn_path}"
            )
            L.append(
                f'puts stderr "ERROR: input_nn.bin not found - place it at: {input_nn_path}"'
            )
            L.append("exit 1")
        L.append("")

    L.append("# Resume ARM execution")
    L.append("con")

    with open(out_path, "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"[gen] XSDB Tcl script written to {out_path}")


def gen_asm_incbin(
    layers: List[LayerInfo],
    out_path: str,
    emit_check: bool = False,
    extra_blobs: Optional[List] = None,
) -> None:
    L: List[str] = []
    L.append("/* Auto-generated by gen_nn_baremetal.py - DO NOT EDIT */")
    L.append("/*")
    L.append(" * VTA static model data: one .incbin section per buffer per layer.")
    L.append(" * Each section is placed at its DRAM address by nn_vta_sections.ld.")
    L.append(
        " * Add this file as a source in your project and INCLUDE nn_vta_sections.ld"
    )
    L.append(" * inside your platform SECTIONS { ... } block.")
    L.append(" */")
    L.append("")

    def emit_section(sec_name: str, abs_bin: str) -> None:
        bin_path = Path(
            abs_bin
        ).as_posix()  # absolute; relativized by create_vitis_workspace.py
        L.append(f'    .section {sec_name}, "a", %progbits')
        L.append(f"    .align {INCBIN_ALIGN_LOG2}")
        if os.path.isfile(abs_bin):
            L.append(f'    .incbin "{bin_path}"')
        else:
            L.append(f"    /* WARNING: binary not found at codegen time: {bin_path} */")
            print(f"WARNING: {abs_bin} not found - section will be empty")
        L.append("")

    for i, layer, buf_type, _ in iter_static_buffers(layers):
        emit_section(
            f".vta_l{i}_{buf_type.lower()}",
            os.path.abspath(layer.bin_files[buf_type]),
        )

    # CPU-op parameter blobs (convtranspose float weights/bias).
    for label, path, _addr, _size in extra_blobs or []:
        emit_section(label, path)

    # Isolation-check golden inputs/outputs (--emit-layer-check only).
    if emit_check:
        for i, layer in enumerate(layers):
            if layer.in_ref_size > 0 and layer.in_ref_file:
                emit_section(f".vta_l{i}_inref", os.path.abspath(layer.in_ref_file))
            if layer.out_ref_size > 0 and layer.out_ref_file:
                emit_section(f".vta_l{i}_outref", os.path.abspath(layer.out_ref_file))

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")
    print(f"[gen] Assembly incbin file written to {out_path}")


def gen_linker_fragment(
    layers: List[LayerInfo],
    ddr_base: int,
    out_path: str,
    emit_check: bool = False,
    extra_blobs: Optional[List] = None,
) -> None:
    L: List[str] = []
    L.append("/* Auto-generated by gen_nn_baremetal.py - DO NOT EDIT              */")
    L.append("/* VTA static model data linker fragment                             */")
    L.append("/*                                                                   */")
    L.append(
        "/* Include this file inside the platform linker script generated.                    */"
    )
    L.append("/* Example (in your lscript.ld):           */")
    L.append("/*   INCLUDE ../gen/nn_vta_sections.ld                                */")
    L.append("")

    L.append("SECTIONS {")
    for i, layer, buf_type, m in iter_static_buffers(layers):
        addr = ddr_base + m.offset
        sec_name = f".vta_l{i}_{buf_type.lower()}"
        L.append(f"{sec_name} 0x{addr:08X} : {{ KEEP(*({sec_name})) }}")

    # CPU-op parameter blobs (convtranspose float weights/bias).
    for label, _path, addr, _size in extra_blobs or []:
        L.append(f"{label} 0x{addr:08X} : {{ KEEP(*({label})) }}")

    # Isolation-check golden inputs/outputs (--emit-layer-check only).
    if emit_check:
        for i, layer in enumerate(layers):
            if layer.in_ref_size > 0 and layer.in_ref_file:
                L.append(
                    f".vta_l{i}_inref 0x{layer.in_ref_addr:08X} :"
                    f" {{ KEEP(*(.vta_l{i}_inref)) }}"
                )
            if layer.out_ref_size > 0 and layer.out_ref_file:
                L.append(
                    f".vta_l{i}_outref 0x{layer.out_ref_addr:08X} :"
                    f" {{ KEEP(*(.vta_l{i}_outref)) }}"
                )

    L.append("}")
    with open(out_path, "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"[gen] Linker fragment written to {out_path}")


def gen_input_tcl(
    layers: List[LayerInfo],
    ddr_base: int,
    comp_dir: str,
    out_path: str,
) -> None:
    L: List[str] = []
    L.append("# Auto-generated by gen_nn_baremetal.py - DO NOT EDIT")
    L.append("#")
    L.append("# Loads input_nn.bin only - static model data is embedded in the ELF.")
    L.append("#")
    L.append("# Usage (from Vitis XSDB console or xsct shell):")
    L.append("#   source load_input.tcl")
    L.append("")
    L.append("connect")
    L.append('targets -set -filter {name =~ "APU*"}')
    L.append("stop")
    L.append("after 500")
    L.append("")

    input_nn_path = os.path.abspath(os.path.join(comp_dir, "input_nn.bin"))
    raw_phys = scratch_addr(layers, ddr_base)
    addr_str = f"0x{raw_phys:08X}"

    L.append("# --- raw network input (scratch - ARM applies im2row at runtime) ---")
    L.append(f'puts "Loading input_nn.bin (raw) -> {addr_str}..."')
    if os.path.isfile(input_nn_path):
        L.append(f"dow -data {{{input_nn_path}}} {addr_str}")
    else:
        L.append(f"# WARNING: input_nn.bin not found at codegen time: {input_nn_path}")
        L.append(
            f'puts stderr "ERROR: input_nn.bin not found - place it at: {input_nn_path}"'
        )
        L.append("exit 1")
    L.append("")
    L.append("# Resume ARM execution")
    L.append("con")

    with open(out_path, "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"[gen] Input-only XSDB Tcl script written to {out_path}")
