#pragma once
// Host-test stub for vta_hw_config.h (normally generated by
// gen_nn_baremetal.py). Fixes the default 32-bit datapath (vta_config.json:
// LOG_*_WIDTH=5, LOG_BLOCK=4) so driver/src/vta_cpu_ops.cc can be compiled and
// exercised on the host. The CPU ops only use the element typedefs and
// VTA_BLOCK_SIZE; the real header's xparameters.h / VCR-base constants are
// intentionally omitted.
#include <cstdint>

using vta_inp_t = std::int32_t;
using vta_out_t = std::int32_t;
using vta_acc_t = std::int32_t;
using vta_wgt_t = std::int32_t;
constexpr int VTA_BLOCK_SIZE = 16;
