/* Auto-generated by the VTA baremetal codegen - DO NOT EDIT */
/*
 * SD-card manifest: file -> DDR address map for the runtime sd loader
 * (driver/src/vta_sd.cc). Copy the staged files in gen/sd_card/ to the
 * root of a FAT32 SD card, then run a DATA_LOADER=sd build.
 */
#ifndef NN_SD_MANIFEST_H
#define NN_SD_MANIFEST_H
#include "vta_sd.h"

/* SD subfolder the files live in (path prefix, trailing slash); empty
 * = card root. The app opens "0:/" NN_SD_DIR <filename>. */
#define NN_SD_DIR ""

static const vta::SdFile nn_sd_static_files[] = {
    {"instructionsQLinearConv1.bin", 0x13DFA000u, 867280u},
    {"uopQLinearConv1.bin", 0x13CFC000u, 1036804u},
    {"weightQLinearConv1.bin", 0x12A31000u, 41472u},
    {"accumulatorQLinearConv1_block.bin", 0x12A3C000u, 9830400u},
    {"instructionsQLinearConv2.bin", 0x171A1000u, 67280u},
    {"uopQLinearConv2.bin", 0x1718E000u, 76804u},
    {"weightQLinearConv2.bin", 0x16B4D000u, 3072u},
    {"accumulatorQLinearConv2_block.bin", 0x16B4E000u, 3276800u},
    {"instructionsQLinearConv3.bin", 0x18166000u, 67280u},
    {"uopQLinearConv3.bin", 0x18153000u, 76804u},
    {"weightQLinearConv3.bin", 0x17B12000u, 3072u},
    {"accumulatorQLinearConv3_block.bin", 0x17B13000u, 3276800u},
    {"instructionsQLinearConv4.bin", 0x1A413000u, 534480u},
    {"uopQLinearConv4.bin", 0x1A3DA000u, 230404u},
    {"weightQLinearConv4.bin", 0x19D97000u, 9216u},
    {"accumulatorQLinearConv4_block.bin", 0x19D9A000u, 3276800u},
    {"instructionsQLinearMul5.bin", 0x1F439000u, 52896u},
    {"uopQLinearMul5.bin", 0x1F435000u, 12804u},
    {"weightQLinearMul5.bin", 0x1EDF4000u, 256u},
    {"accumulatorQLinearMul5_block.bin", 0x1EDF5000u, 3276800u},
    {"instructionsQLinearConv6.bin", 0x1C732000u, 534480u},
    {"uopQLinearConv6.bin", 0x1C6F9000u, 230404u},
    {"weightQLinearConv6.bin", 0x1C0B6000u, 9216u},
    {"accumulatorQLinearConv6_block.bin", 0x1C0B9000u, 3276800u},
    {"instructionsQLinearConv8.bin", 0x1EA51000u, 534480u},
    {"uopQLinearConv8.bin", 0x1EA18000u, 230404u},
    {"weightQLinearConv8.bin", 0x1E3D5000u, 9216u},
    {"accumulatorQLinearConv8_block.bin", 0x1E3D8000u, 3276800u},
    {"instructionsQLinearMul9.bin", 0x1FDAB000u, 52896u},
    {"uopQLinearMul9.bin", 0x1FDA7000u, 12804u},
    {"weightQLinearMul9.bin", 0x1F766000u, 256u},
    {"accumulatorQLinearMul9_block.bin", 0x1F767000u, 3276800u},
    {"instructionsQLinearConv10.bin", 0x1616A000u, 534480u},
    {"uopQLinearConv10.bin", 0x16131000u, 230404u},
    {"weightQLinearConv10.bin", 0x15AEE000u, 9216u},
    {"accumulatorQLinearConv10_block.bin", 0x15AF1000u, 3276800u},
};
#define NN_SD_NUM_STATIC 36u

#define NN_SD_HAS_INPUT 0

#define NN_SD_HAS_REFS 0

#endif /* NN_SD_MANIFEST_H */
