/* Auto-generated by gen_nn_baremetal.py - DO NOT EDIT */
/*
 * SD-card manifest: file -> DDR address map for the runtime sd loader
 * (driver/src/vta_sd.cc). Copy the staged files in gen/sd_card/ to the
 * root of a FAT32 SD card, then run a DATA_LOADER=sd build.
 */
#ifndef NN_SD_MANIFEST_H
#define NN_SD_MANIFEST_H
#include "vta_sd.h"

/* SD subfolder the files live in (path prefix, trailing slash); empty
 * = card root. The app opens "0:/" NN_SD_DIR <filename>. */
#define NN_SD_DIR ""

static const vta::SdFile nn_sd_static_files[] = {
    {"instructionsQLinearConv1.bin", 0x03E18000u, 867280u},
    {"uopQLinearConv1.bin", 0x03D1A000u, 1036804u},
    {"weightQLinearConv1.bin", 0x02A31000u, 165888u},
    {"accumulatorQLinearConv1_block.bin", 0x02A5A000u, 9830400u},
    {"instructionsQLinearConv2.bin", 0x071C7000u, 67280u},
    {"uopQLinearConv2.bin", 0x071B4000u, 76804u},
    {"weightQLinearConv2.bin", 0x06B71000u, 12288u},
    {"accumulatorQLinearConv2_block.bin", 0x06B74000u, 3276800u},
    {"instructionsQLinearConv3.bin", 0x0818E000u, 67280u},
    {"uopQLinearConv3.bin", 0x0817B000u, 76804u},
    {"weightQLinearConv3.bin", 0x07B38000u, 12288u},
    {"accumulatorQLinearConv3_block.bin", 0x07B3B000u, 3276800u},
    {"instructionsQLinearConv4.bin", 0x0A441000u, 534480u},
    {"uopQLinearConv4.bin", 0x0A408000u, 230404u},
    {"weightQLinearConv4.bin", 0x09DBF000u, 36864u},
    {"accumulatorQLinearConv4_block.bin", 0x09DC8000u, 3276800u},
    {"instructionsQLinearMul5.bin", 0x0F473000u, 52896u},
    {"uopQLinearMul5.bin", 0x0F46F000u, 12804u},
    {"weightQLinearMul5.bin", 0x0EE2E000u, 1024u},
    {"accumulatorQLinearMul5_block.bin", 0x0EE2F000u, 3276800u},
    {"instructionsQLinearConv6.bin", 0x0C766000u, 534480u},
    {"uopQLinearConv6.bin", 0x0C72D000u, 230404u},
    {"weightQLinearConv6.bin", 0x0C0E4000u, 36864u},
    {"accumulatorQLinearConv6_block.bin", 0x0C0ED000u, 3276800u},
    {"instructionsQLinearConv8.bin", 0x0EA8B000u, 534480u},
    {"uopQLinearConv8.bin", 0x0EA52000u, 230404u},
    {"weightQLinearConv8.bin", 0x0E409000u, 36864u},
    {"accumulatorQLinearConv8_block.bin", 0x0E412000u, 3276800u},
    {"instructionsQLinearMul9.bin", 0x0FDE5000u, 52896u},
    {"uopQLinearMul9.bin", 0x0FDE1000u, 12804u},
    {"weightQLinearMul9.bin", 0x0F7A0000u, 1024u},
    {"accumulatorQLinearMul9_block.bin", 0x0F7A1000u, 3276800u},
    {"instructionsQLinearConv10.bin", 0x0618E000u, 534480u},
    {"uopQLinearConv10.bin", 0x06155000u, 230404u},
    {"weightQLinearConv10.bin", 0x05B0C000u, 36864u},
    {"accumulatorQLinearConv10_block.bin", 0x05B15000u, 3276800u},
};
#define NN_SD_NUM_STATIC 36u

#define NN_SD_HAS_INPUT 0

#define NN_SD_HAS_REFS 0

#endif /* NN_SD_MANIFEST_H */
