/**
 * run_nn_debug.cc - Per-layer VTA isolation check (debug, XSCT method).
 *
 * Like run_nn.cc, DDR is pre-initialized via the XSCT script generated by
 * host/gen_nn_baremetal.py.  In addition to the static model data
 * (INSN/UOP/WGT/ACC), the --emit-layer-check generation embeds per-layer
 * golden inputs/outputs (fsim VTA_DUMP_LAYERS=1 dumps) and the nn_debug[]
 * table (nn_debug_map.h).
 *
 * Instead of running the full chained pipeline, each VTA layer is executed in
 * isolation on its golden input and its raw output is compared against the
 * golden output - so the first failing layer is the true source of corruption.
 *
 * Build with NN_CHECK_LAYERS defined; otherwise run_nn_debug() is a no-op.
 *
 * To regenerate headers:
 *   python3 host/gen_nn_baremetal.py <compiler_output_dir>      \
 *       --ddr-base    0x10000000                                \
 *       --outdir      gen                                       \
 *       --config-json ../../../config/vta_config.json           \
 *       --emit-layer-check --ref-dir <repo>/simulators_output
 */

#include "nn_ddr_map.h"
#include "nn_debug_map.h"
#include "vta_board.h"
#include "vta_hw_config.h"
#include "vta_nn.h"
#include "vta_nn_debug.h"
extern "C" {
#include "xil_printf.h"
}

int main() {
  vta::board_init();
  xil_printf("=== VTA NN isolation runner: %u layer(s) ===\r\n",
             static_cast<unsigned>(NN_NUM_DEBUG));

  bool ok = vta::run_nn_debug(VTA_VCR_BASE, nn_layers, NN_NUM_LAYERS, nn_debug,
                              NN_NUM_DEBUG);

  if (!ok)
    return -1;
  xil_printf("=== isolation check done ===\r\n");
  return 0;
}
