/**
 * run_nn.cc - Multi-layer VTA inference (XSCT method).
 *
 * DDR memory is pre-initialized via the XSCT script generated by
 * host/gen_nn_baremetal.py (load_nn_static.tcl): static model data
 * (INSN/UOP/WGT/ACC) is loaded before this binary starts; input_nn.bin
 * is loaded separately via load_input.tcl.
 *
 * To regenerate headers from a compiler output directory:
 *   python3 host/gen_nn_baremetal.py <compiler_output_dir> \
 *       --ddr-base    0x10000000                           \
 *       --outdir      gen                                  \
 *       --config-json ../../../config/vta_config.json
 */

#include "nn_ddr_map.h"
#include "nn_exec_plan.h"
#include "vta_board.h"
#include "vta_hw_config.h"
#include "vta_nn.h"
#include <cstdlib>
extern "C" {
#include "xil_printf.h"
}

int main() {
  vta::board_init();
  xil_printf("=== VTA NN runner: %u step(s) ===\r\n",
             static_cast<unsigned>(NN_NUM_STEPS));

  std::uint32_t float_bytes = 0;
  bool ok = false;
  float *float_buf = vta::run_nn(VTA_VCR_BASE, nn_exec_steps, NN_NUM_STEPS,
                                 nn_layers, NN_NUM_LAYERS, &float_bytes, &ok);
  std::free(float_buf);

  if (!ok)
    return -1;
  xil_printf("=== NN done ===\r\n");
  return 0;
}
