package fpga.host.exporters

import fpga.host.models._
import fpga.host.models.Model.LayerInfo
import fpga.host.transform.{ExecSteps, MemoryLayout}

/** Rendering for the per-layer / per-CPU-op isolation-check headers. Translated
  * from host/nnbaremetal/debug_emit.py. The layout pass that fills in each
  * layer's golden regions lives in
  * [[fpga.host.models.MemoryLayout.assignLayerCheckRegions]]; this object only
  * renders the `nn_debug_map.h` / `nn_cpu_debug_map.h` tables.
  */
private[exporters] object DebugRender {

  /** Render `nn_debug_map.h`: the vta::DebugLayerDesc nn_debug[] table. */
  def debugMap(t: DebugMap): String = {
    val layers = t.layers
    val header =
      s"""/* Auto-generated by the VTA baremetal codegen - DO NOT EDIT */
         |#pragma once
         |#include \"vta_nn_debug.h\"
         |
         |#define NN_NUM_DEBUG ${layers.length}
         |
         |static const vta::DebugLayerDesc nn_debug[NN_NUM_DEBUG] = {""".stripMargin
    val layerEntries = layers.zipWithIndex.map { case (layer, i) =>
      emitDebugEntryMap(layer, i)
    }
    header + "\n" + layerEntries.mkString(",\n") + "\n};\n\n"
  }

  private def emitDebugEntryMap(layer: LayerInfo, id: Int) = {
    val c = layer.check
    s"""    /* layer $id  suffix="${layer.suffix}" */
       |    {
       |        .layer_idx     = ${id}u,
       |        .in_ref_phys   = ${Model.hex32(c.fold(0L)(_.inRefAddr))},
       |        .in_ref_bytes  = ${Model.hex32(c.fold(0L)(_.inRefSize))},
       |        .in_dst_phys   = ${Model.hex32(c.fold(0L)(_.inDstAddr))},
       |        .out_ref_phys  = ${Model.hex32(c.fold(0L)(_.outRefAddr))},
       |        .out_ref_bytes = ${Model.hex32(c.fold(0L)(_.outRefSize))},
       |        .name          = "${layer.suffix}",
       |    }""".stripMargin
  }

  /** One CPU-debug-table entry. Mirrors the 11-tuple built in debug_emit.py. */
  private final case class CpuEntry(
    stepIdx: Int,
    kind: String,
    name: String,
    outPhys: Long,
    outBytes: Long,
    refPhys: Long,
    refBytes: Long,
    elemBytes: Int,
    srcRefPhys: Long,
    srcRefBytes: Long,
    srcDstPhys: Long
  )

  /** Render `nn_cpu_debug_map.h`: the DebugCpuStep nn_cpu_debug[] table.
    *
    * One entry per CPU step whose output buffer equals a VTA layer's golden
    * input dump (FORMAT_INPUT / IM2ROW / INT32_CHAIN). The stepIdx field is the
    * index of the corresponding entry in nn_exec_steps[] - the same counter
    * gen_exec_plan_header() uses when emitting the plan, replayed here so
    * lookups stay in sync.
    */
  def cpuDebugMap(t: CpuDebugMap): String = {
    val depInfo = t.dep
    val layers = t.layers
    val cfg = t.cfg
    val suffixToIdx = t.suffixToIdx
    val ddrBase = t.ddrBase

    val inpBytes = HwConfig.elemBytes(cfg.logInpWidth)
    val accBytes = HwConfig.elemBytes(cfg.logAccWidth)
    val logOutWidth = cfg.logOutWidth
    val rawPhys = MemoryLayout.scratchAddr(layers, ddrBase)
    val rawSize = Model
      .inputNnPath(t.refDir)
      .filter(Model.isFile)
      .map(p => os.size(os.Path(p, os.pwd)))
      .getOrElse(0L)

    val execSteps = ExecSteps.of(depInfo, layers, suffixToIdx, logOutWidth)

    // Resolve (srcRefPhys, srcRefBytes, srcDstPhys) for one op. Returns
    // (0, 0, 0) when no golden source is available; the runtime then falls
    // back to whatever is preloaded in the source buffer.
    def srcIsolation(kind: String, layerName: String): (Long, Long, Long) = {
      if (kind == "format_input") {
        // Raw image is loaded to rawPhys by the debugger; the source buffer
        // already holds the golden, so point src at it (self-referential).
        if (rawSize == 0L) (0L, 0L, 0L)
        else (rawPhys, rawSize, rawPhys)
      } else {
        // im2row / int32_chain: source is the producing layer's OUT buffer; the
        // golden is that producer's outRef (pre-rescale output<suffix>.bin).
        val ld = depInfo.layers.get(layerName)
        val depName = ld.flatMap(d => d.deps.headOption).getOrElse("")
        val prodIdx = suffixToIdx.getOrElse(depName, -1)
        if (prodIdx < 0) (0L, 0L, 0L)
        else {
          val producer = layers(prodIdx)
          if (producer.check.forall(_.outRefSize == 0L)) (0L, 0L, 0L)
          else {
            val pc = producer.check.get
            val srcDst = ddrBase + producer.mem("OUT").offset
            (pc.outRefAddr, pc.outRefSize, srcDst)
          }
        }
      }
    }

    // Per qualifying step: at most one table entry plus any skip messages,
    // derived in one pass (was two mutable ArrayBuffers appended in a loop).
    val perStep: Seq[(Option[CpuEntry], List[String])] =
      execSteps
        .filter(s =>
          Set("format_input", "im2row", "int32_chain").contains(s.kind)
        )
        .map { step =>
          val layerName = step.layerName
          val consumerIdx = suffixToIdx.getOrElse(layerName, -1)
          val consumer =
            if (consumerIdx >= 0) Some(layers(consumerIdx)) else None
          val elemBytes = if (step.kind == "int32_chain") accBytes else inpBytes
          val name = step.kind match {
            case "format_input" => s"format_$layerName"
            case "im2row"       => s"im2row_$layerName"
            case _              => s"int32_chain_$layerName"
          }
          if (
            consumer.isEmpty || consumer.get.check.forall(_.inRefSize == 0L)
          ) {
            (None, List(s"$name (no golden input embedded)"))
          } else {
            val (srcRefPhys, srcRefBytes, srcDstPhys) =
              srcIsolation(step.kind, layerName)
            val skip =
              if (srcRefBytes == 0L)
                List(s"$name (no upstream golden - isolation fallback)")
              else Nil
            val ck = consumer.get.check.get
            val entry = CpuEntry(
              step.stepIdx,
              step.kind,
              name,
              ck.inDstAddr,
              ck.inRefSize,
              ck.inRefAddr,
              ck.inRefSize,
              elemBytes,
              srcRefPhys,
              srcRefBytes,
              srcDstPhys
            )
            (Some(entry), skip)
          }
        }
    val entries = perStep.flatMap(_._1)
    val skipped = perStep.flatMap(_._2)

    // Emit the header.
    val header =
      s"""/* Auto-generated by the VTA baremetal codegen - DO NOT EDIT */
         |#pragma once
         |#include "vta_cpu_ops_debug.h"
         |
         |/*
         | * Coverage: only CPU ops whose output buffer equals a VTA layer's
         | * golden INP/ACC dump are checked (FORMAT_INPUT / IM2ROW / INT32_CHAIN).
         | * Other CPU ops (rescale / qadd / concat / dequant / quant) are
         | * absent from the table and silently skipped at runtime.
         | *
         | * Isolation-mode source fields (src_ref_*, src_dst_phys) preload each
         | * op's INPUT with a known-good golden (raw image for format_input, the
         | * producer layer's pre-rescale out_ref for im2row/int32_chain) so a bad
         | * upstream layer does not cascade.  The runtime replays the producer
         | * rescale before the reshape.  Entries left at 0 (no embedded golden,
         | * e.g. --emit-layer-check not run) fall back to the preloaded buffer.
         | ${if (skipped.nonEmpty) {
          ("*" +: "* Skipped at codegen:" +: skipped.map(s => s"*   - $s"))
            .mkString("\n      | ")
        }}
         | */
         |""".stripMargin
    val defines = s"""
                     |#define NN_NUM_CPU_DEBUG ${entries.length}u
                     |
                     |""".stripMargin
    val body = (if (entries.isEmpty) {
                  // C++ requires at least one element for an array; zero-initialised stub
                  // is harmless because NN_NUM_CPU_DEBUG == 0 so the runtime never reads
                  // it. Keeps the apps that reference nn_cpu_debug[] compiling.
                  s"static const vta::DebugCpuStep nn_cpu_debug[1] = {};"
                } else {
                  val d =
                    "static const vta::DebugCpuStep nn_cpu_debug[NN_NUM_CPU_DEBUG] = {"
                  val cpuEntries =
                    entries
                      .map(emitDebugCpuStep)
                      .mkString(",\n")
                  d ++ "\n" ++ cpuEntries ++ "\n};"
                })
    header ++ defines ++ body ++ "\n\n"
  }

  private def emitDebugCpuStep(entry: CpuEntry) = {
    s"""    /* ${entry.kind} */
       |    {
       |        .step_idx      = ${entry.stepIdx}u,
       |        .out_phys      = ${Model.hex32(entry.outPhys)},
       |        .out_bytes     = ${Model.hex32(entry.outBytes)},
       |        .ref_phys      = ${Model.hex32(entry.refPhys)},
       |        .ref_bytes     = ${Model.hex32(entry.refBytes)},
       |        .elem_bytes    = std::uint16_t(${entry.elemBytes}u),
       |        ._pad          = std::uint16_t(0u),
       |        .src_ref_phys  = ${Model.hex32(entry.srcRefPhys)},
       |        .src_ref_bytes = ${Model.hex32(entry.srcRefBytes)},
       |        .src_dst_phys  = ${Model.hex32(entry.srcDstPhys)},
       |        .name          = "${entry.name}",
       |    }""".stripMargin
  }
}

/** `Emittable` instances for the debug-check artifacts. */
trait DebugEmitters {
  implicit val debugMapIsEmittable: Emittable[DebugMap] =
    Emittable(DebugRender.debugMap)
  implicit val cpuDebugMapIsEmittable: Emittable[CpuDebugMap] =
    Emittable(DebugRender.cpuDebugMap)
}
