# board_params.tcl - generated by the fpga.synthesis.BuildFpga task; do not edit by hand.
# board: vck190

set board_name {vck190}
set part {xcvc1902-vsva2197-2MP-e-S}
set board_part {xilinx.com:vck190:part0:3.2}
set is_versal {true}
set ps_ip {xilinx.com:ip:versal_cips:3.4}
set ps_cell {versal_cips_0}
set ps_preset_rule {xilinx.com:bd_rule:cips}
set ps_preset_config {board_preset {Yes} boot_config {JTAG} configure_noc {None} debug_config {Custom} design_flow {Full System} mc_type {None} num_mc {1} pl_clocks {None} pl_resets {None}}
set board_repo {}
set pl_clock_mhz {100}
set pl_clock_property {}
set vta_cell {VTA_0}
set vta_vlnv {onera:user:VTA:0.2.0}
set ip_repo {/fixed/ip_repo}
set out_dir {/fixed/out}
set proj_dir {/fixed/out/project}
set export_dir {/fixed/out}
set jobs {4}

set ps_config {CLOCK_MODE {Custom} PS_PL_CONNECTIVITY_MODE {Custom} PS_PMC_CONFIG {CLOCK_MODE {Custom} PS_PL_CONNECTIVITY_MODE {Custom} PMC_CRP_PL0_REF_CTRL_FREQMHZ {100} PS_USE_PMCPL_CLK0 {1} PS_NUM_FABRIC_RESETS {1} PS_USE_M_AXI_FPD {1} PS_M_AXI_FPD_DATA_WIDTH {32} PS_USE_FPD_CCI_NOC {1} PS_USE_FPD_CCI_NOC0 {1} PS_USE_FPD_CCI_NOC1 {1} PS_USE_FPD_CCI_NOC2 {1} PS_USE_FPD_CCI_NOC3 {1} PS_USE_NOC_LPD_AXI0 {1} PMC_USE_PMC_NOC_AXI0 {1}}}
set noc_config {MC_SYSTEM_CLOCK {Differential} MC_CHAN_REGION1 {DDR_LOW1}}
set port_vta_dram_master {m_axi_gmem}
set port_vta_ctrl_slave {s_axi_control}
set port_vta_clk {ap_clk}
set port_vta_resetn {ap_rst_n}
set port_ps_dram_slave {axi_noc_0/S06_AXI}
set port_ps_ctrl_master {M_AXI_FPD}
set port_ps_clk {pl0_ref_clk}
set port_ps_resetn {pl0_resetn}
set versal_ch0 {ch0_lpddr4_c0}
set versal_ch1 {ch1_lpddr4_c0}
set versal_clk {lpddr4_sma_clk1}
set ps_clk_aclks {m_axi_fpd_aclk}

set addresses {{versal_cips_0/M_AXI_FPD VTA_0/s_axi_control/reg0 0xA4000000 0x00010000} {VTA_0/m_axi_gmem axi_noc_0/S06_AXI/C0_DDR_LOW0 0x00000000 0x80000000} {versal_cips_0/FPD_CCI_NOC_0 axi_noc_0/S00_AXI/C3_DDR_LOW0 0x00000000 0x80000000} {versal_cips_0/FPD_CCI_NOC_0 axi_noc_0/S00_AXI/C3_DDR_LOW1 0x000800000000 0x80000000} {versal_cips_0/FPD_CCI_NOC_1 axi_noc_0/S01_AXI/C2_DDR_LOW0 0x00000000 0x80000000} {versal_cips_0/FPD_CCI_NOC_1 axi_noc_0/S01_AXI/C2_DDR_LOW1 0x000800000000 0x80000000} {versal_cips_0/FPD_CCI_NOC_2 axi_noc_0/S02_AXI/C0_DDR_LOW0 0x00000000 0x80000000} {versal_cips_0/FPD_CCI_NOC_2 axi_noc_0/S02_AXI/C0_DDR_LOW1 0x000800000000 0x80000000} {versal_cips_0/FPD_CCI_NOC_3 axi_noc_0/S03_AXI/C1_DDR_LOW0 0x00000000 0x80000000} {versal_cips_0/FPD_CCI_NOC_3 axi_noc_0/S03_AXI/C1_DDR_LOW1 0x000800000000 0x80000000} {versal_cips_0/LPD_AXI_NOC_0 axi_noc_0/S04_AXI/C3_DDR_LOW0 0x00000000 0x80000000} {versal_cips_0/LPD_AXI_NOC_0 axi_noc_0/S04_AXI/C3_DDR_LOW1 0x000800000000 0x80000000} {versal_cips_0/PMC_NOC_AXI_0 axi_noc_0/S05_AXI/C2_DDR_LOW0 0x00000000 0x80000000} {versal_cips_0/PMC_NOC_AXI_0 axi_noc_0/S05_AXI/C2_DDR_LOW1 0x000800000000 0x80000000}}
set address_excludes {{VTA_0/m_axi_gmem axi_noc_0/S06_AXI/C0_DDR_LOW1}}

