# Workflow executing VTA simulator and perform basic tests

name: Standalone VTA CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment_setup/standalone-vta.yml
          activate-environment: standalone-vta
      - name: Activate env
        run: conda activate standalone-vta
      - name: List packages
        run: |
          echo $CONDA_DEFAULT_ENV
          conda list
      - name: Build Lenet5 instructions and data
        run: make lenet5