# Workflow executing VTA simulator and perform basic tests

name: Standalone VTA CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          environment-file: environment_setup/standalone-vta.yml
          activate-environment: standalone-vta
      - name: Build Lenet5 instructions and data
        run: make lenet5
      - name: Display compiler results
        run: cat compiler_output/prompt_data.txt
      - name: Display simulator results
        run: cat simulators_output/fsim_report.txt