# Workflow executing VTA simulator and perform basic tests

name: Standalone VTA Update CI

on:
  push:
    branches: [ "sim_verilator_backend" ]
  workflow_dispatch:
    


permissions:
  contents: read

jobs:
  functional-simulator-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup python
        uses: actions/setup-python@v6
        with: 
          python-version-file: "src/compiler/.python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.11"
      - name: Sync dependencies
        run: cd src/compiler && uv sync
      - name: Tests VTA compiler and functional simulator
        run: |
          source src/compiler/.venv/bin/activate
          cd examples && make compile_and_run

  cycle-accurate-simulator-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Cache Scala
        uses: coursier/cache-action@v6
      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          jvm: adopt:11
          apps: sbt
      - name: Setup Z3
        id: z3
        uses: cda-tum/setup-z3@v1
      - name: Install Verilator
        run: |
          sudo apt-get install verilator
          verilator --version
      - name: Run mill tests
        run: |
          cd src/simulators/cycle_accurate_simulator
          ./mill test.unittest
      - name: Run sbt tests
        run: |
          cd src/simulators/cycle_accurate_simulator
          sbt test

  sim-cycle-accurate:
      needs: [functional-simulator-test, cycle-accurate-simulator-test]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v6
        - name: Cache Scala
          uses: coursier/cache-action@v6
        - name: Setup Scala
          uses: coursier/setup-action@v1
          with:
            jvm: adopt:11
            apps: sbt
        - name: Setup Z3
          id: z3
          uses: cda-tum/setup-z3@v1
        - name: Install Verilator
          run: |
            sudo apt-get install verilator
            verilator --version
        - name: Setup python
          uses: actions/setup-python@v6
          with: 
            python-version-file: "src/compiler/.python-version"
        - name: Install uv
          uses: astral-sh/setup-uv@v7
          with:
            version: "0.10.11"
        - name: Sync dependencies
          run: cd src/compiler && uv sync
        - name: Emit simulation SystemVerilog files
          run: |
              cd src/simulators/cycle_accurate_simulator
              ./mill emitVtaSimConfig
        - name: Build simulator with verilated backend
          run: |
            cd src/simulators/functional_simulator
            SIM_THREADS=2 make build/fsim_single_layer_rtl
        - name: Compile small gemm test
          run: |
            source src/compiler/.venv/bin/activate
            cd examples
            make -s test_gemm
        - name: Test the functional simulation
          run: |
            cd src/simulators/functional_simulator
            ./build/fsim_single_layer_rtl
        - name: Test the cycle accurate simulation 
          run: |
            cd src/simulators/functional_simulator
            ./build/fsim_single_layer_rtl --verilator
