# Workflow executing VTA simulator and perform basic tests

name: Standalone VTA CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Manual workflow execution
  workflow_dispatch:

permissions:
  contents: read

jobs:
  functional-simutator-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          environment-file: environment_setup/standalone-vta.yml
          activate-environment: standalone-vta
      - name: Tests VTA compiler and functional simulator
        run: cd examples && make test

  cycle-accurate-simulator-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Setup Z3
        id: z3
        uses: cda-tum/setup-z3@v1
      - name: Run tests
        run: |
          cd src/simulators/cycle_accurate_simulator
          sbt test