# Workflow executing VTA simulator and perform basic tests

name: Standalone VTA Update CI

on:
  push:
    branches: [ "chiselsim_dev" ]
  workflow_dispatch:
    


permissions:
  contents: read

jobs:
  functional-simulator-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup python
        uses: actions/setup-python@v6
        with: 
          python-version-file: "src/compiler/.python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.11"
      - name: Sync dependencies
        run: cd src/compiler && uv sync
      - name: Tests VTA compiler and functional simulator
        run: |
          source src/compiler/.venv/bin/activate
          cd examples && make compile_and_run

  chisel-unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Cache Scala
        uses: coursier/cache-action@v6
      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          jvm: adopt:11
      - name: Install Verilator
        run: |
          sudo apt-get install verilator
          verilator --version
      - name: Run mill tests
        run: |
          cd src/simulators/cycle_accurate_simulator
          ./mill test.unittest

  cycle-accurate-simulator-test:
      needs: [functional-simulator-test, chisel-unittests]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v6
        - name: Cache Scala
          uses: coursier/cache-action@v6
        - name: Setup Scala
          uses: coursier/setup-action@v1
          with:
            jvm: adopt:11
        - name: Install Verilator
          run: |
            sudo apt-get install verilator
            verilator --version
        - name: Setup python
          uses: actions/setup-python@v6
          with: 
            python-version-file: "src/compiler/.python-version"
        - name: Install uv
          uses: astral-sh/setup-uv@v7
          with:
            version: "0.10.11"
        - name: Sync dependencies
          run: cd src/compiler && uv sync
        - name: Compile cycle accurate simulator
          run: cd examples && SIM_THREADS=2 make -s vsim_compile
        - name: Compile ONNX
          run: |
            source src/compiler/.venv/bin/activate
            cd examples
            make -s nn_compiler
        - name: Compile VTA
          run: |
            source src/compiler/.venv/bin/activate
            cd examples
            make -s vta_compiler
        - name: Compute reference 
          run: |
            source src/compiler/.venv/bin/activate
            cd examples
            make -s reference
        - name: Simulate the inference 
          run: |
            cd examples
            make -s vsim_inference
        - name: Check output against reference
          run: |
            source src/compiler/.venv/bin/activate
            cd examples
            make check_vsim
